- cmd/poller/options/options.go
> Don't overwrite cobra initialized config

- README.md
> Improve download instructions in README

- Makefile
- README.md
- docker/allPollerInOneContainer/Dockerfile
> make file changes

- cmd/exporters/influxdb/README.md
> Remove angry red from GitHub

- cmd/harvest/harvest.go
- cmd/tools/doctor/doctor.go
- cmd/tools/doctor/doctor_test.go
- cmd/tools/doctor/testConfig.yml
- go.mod
- go.sum
- pkg/conf/conf.go
* Use `gopkg.in/yaml.v3` to parse yml - better parser with comment support
* Create a `HarvestConfig` struct - biggest advantage of this struct is it allows us to move away from [StringlyTyped](http://wiki.c2.com/?StringlyTyped) code
* Add `harvest doctor` cmd which:
* Validates config file passed via `--config`
* Prints a sanitized version of the config file: removing comments, usernames, passwords, and auth tokens - the goal is to include the output of this for every issue
* Testcase for sanitizing and struct creation
Remaining
* Evaluate the effort to replace the current config parsing code with `HarvestConfig` struct
* Add more checks to `checkAll`
* Evaluate the effort to create structs for everything in `conf/` folder. Haven't seen anything that looks problematic from a schema point …
> Add harvest doctor command

- pkg/api/ontapi/zapi/client.go
TODO add unit tests. I am exploring mock frameworks atm.
> InsecureSkipVerify with basicauth

- cmd/exporters/prometheus/httpd.go
> Correct httpd logging pattern

- cmd/collectors/zapi/plugins/shelf/shelf.go
> Shelf purges instances too soon

- pkg/logging/logger.go
> enable caller for zerolog

- cmd/exporters/influxdb/README.md
- cmd/exporters/influxdb/influxdb.go
- cmd/exporters/influxdb/influxdb_test.go
Thanks to @steverweber for the suggestion
Fixes #63
> InfluxDB exporter should pass url unchanged

- grafana/prometheus/harvest_dashboard_aggregate.json
- grafana/prometheus/harvest_dashboard_cluster.json
- grafana/prometheus/harvest_dashboard_metadata.json
- grafana/prometheus/harvest_dashboard_network.json
- grafana/prometheus/harvest_dashboard_node.json
- grafana/prometheus/harvest_dashboard_shelf.json
> Prometheus dashboards don't load when exemplar = true

- cmd/exporters/prometheus/httpd.go
- cmd/exporters/prometheus/prometheus.go
- cmd/poller/options/options.go
- cmd/poller/poller.go
Changing the PrometheusPort arg from string to int along with the appropriate checks and usage.
make build and make test are passing locally.
> PrometheusPort should be int

- cmd/collectors/unix/main.go
- cmd/harvest/harvest.go
- cmd/poller/options/options.go
- cmd/poller/poller.go
- deb/postinst
- deb/postrm
- pkg/conf/conf.go
- pkg/util/util.go
- rpm/spec
- service/harvest.conf
- Improve poller detection by injecting IS_HARVEST into exec-ed process's
environment.
- Simplify management code and improve accuracy
> Remove pidfiles

- grafana/prometheus/harvest_dashboard_cluster.json
- grafana/prometheus/harvest_dashboard_node.json
- grafana/prometheus/harvest_dashboard_volume.json
changed from Thoughput to Throughput.
> Correcting Grafana Cluster Dashboard Typo plus other same typos

- service/contrib/README.md
> Add README on how to setup per poller systemd

- grafana/prometheus/harvest_dashboard_network.json
For testing,
Grafana dashboard: http://10.249.31.251:3000/d/-yht8Qgnz/netapp-detail-network?orgId=1&refresh=1m
> network dashboard: percent limit from 0-100 to 0-1

- harvest.cue
Validate and eval with:
```
cue vet harvest.cue harvest.yml
cue eval -s harvest.cue harvest.yml
```
> Add Harvest CUE validation and type-checking

- pkg/util/util.go
harvest status works on Mac
Marching ever closer to `shirou/gopsutil` :)
> Make GetCmdLine work on Darwin so that

- grafana/prometheus/harvest_dashboard_node.json
Grafana dropdown. Fixes part of #186
> Cluster should be filtered by datacenter in

- grafana/prometheus/harvest_dashboard_node.json
Changes required in : Average latency, Throughput and Top average Iops graphs.
> Node Dashboard / all nodes are shown

- grafana/prometheus/harvest_dashboard_volume.json
local grafana url: http://10.249.24.232:3000/d/oddjIegnk/netapp-detail-volume?orgId=1&var-Datacenter=DC-03&var-Cluster=F8080-32-25&var-SVM=SMQA&var-Volume=vol_volume_all_dest&var-TopResources=5&refresh=1m
> support svm/volume filter on 6 graphs in volume dashboard

- CHANGELOG.md
Created last night, will update with the most recent later this morning
> Update changelog for 21.05.3

- conf/zapi/cdot/9.8.0/lun.yaml
> Use correct counter name for lun

- cmd/harvest/harvest.go
> fix: don't add debug when foregrounding

- cmd/poller/collector/collector.go
> fix: poller lag

- cmd/exporters/prometheus/prometheus_test.go
test was part of PR #193, but I forgot to commit on time
> add test for filterMetatags

- cmd/tools/grafana/grafana.go
- cmd/tools/grafana/grafana_test.go
Addresses feature request #87
Re-opened a PR #228 and fixed issues in the review.
> Grafana global prefix - re-opened PR

- cmd/tools/doctor/testdata/testConfig.yml
- pkg/conf/conf_test.go
> test: add test for poller panic in #271

- grafana/prometheus/harvest_dashboard_volume.json
> feat: (bug) volume dashboard fill grade graphic change

- pkg/matrix/matrix.go
- pkg/matrix/matrix_test.go
> fix: Harvest Collector panics from ZapiPerf:Volume collector

- cmd/collectors/zapi/plugins/shelf/shelf.go
- conf/zapi/cdot/9.8.0/shelf.yaml
feat: Shelf metrics should report on op-status for components like fan, psu.
shelf_sensor_labels:
shelf_sensor_labels{cluster="F8080-32-25", datacenter="DC-03", instance="localhost:12991", job="prometheus1", location="rear of the shelf on the lower left power supply", sensor_id="1", shelf="1.0", status="normal"} | 1
-- | --
shelf_sensor_labels{cluster="F8080-32-25", datacenter="DC-03", instance="localhost:12991", job="prometheus1", location="rear of the shelf on the lower left power supply", sensor_id="1", shelf="1.10", status="normal"} | 1
shelf_sensor_labels{cluster="F8080-32-25", datacenter="DC-03", instance="localhost:12991", job="prometheus1", location="rear of the shelf on the lower left power supply", sensor_id="2", shelf="1.0", status="normal"} | 1 …
> feat: shelf metrics should report on op-status for components

- cmd/collectors/zapi/plugins/shelf/shelf.go
Fix for :final comment of customer in #295 to add shelf_fan_status like metrics.
Note: due to if block indentation, it shows too many changes but it;s not. :)
We can do like this, but each child would have different possible values which is ugly way to write all of them, And as these are child of shelf object, so normal value would be mapped to 1 and rest all are mapped to 0
//varmetricsForStatus=map[string]string{
//"cooling-fans":"normal",
//"current-sensors":"normal",
//"power-supply-units":"normal",
//"temperature-sensors":"normal",
//"voltage-sensors":"normal",
//}
programmatically changed the fan_op_status to unknown, this is the result of that:
> feat: shelf child metrics correction to add shelf_fan_status, etc

- cmd/poller/plugin/README.md
- cmd/poller/plugin/label_agent/label_agent.go
- cmd/poller/plugin/label_agent/label_agent_test.go
- cmd/poller/plugin/label_agent/parse_rules.go
- conf/zapi/cdot/9.8.0/aggr.yaml
- conf/zapi/cdot/9.8.0/disk.yaml
- conf/zapi/cdot/9.8.0/lun.yaml
- conf/zapi/cdot/9.8.0/node.yaml
- conf/zapi/cdot/9.8.0/shelf.yaml
- conf/zapi/cdot/9.8.0/status.yaml
- conf/zapi/cdot/9.8.0/subsystem.yaml
- conf/zapi/cdot/9.8.0/volume.yaml
my prometheus url:
http://10.249.29.132:9090/graph?g0.expr=volume_new_status&g0.tab=1&g0.stacked=0&g0.range_input=1h
> feat: adding value_to_num mapping rules

- grafana/prometheus/harvest_dashboard_aggregate.json
- grafana/prometheus/harvest_dashboard_cluster.json
- grafana/prometheus/harvest_dashboard_node.json
- grafana/prometheus/harvest_dashboard_shelf.json
- grafana/prometheus/harvest_dashboard_volume.json
Grafana URL: http://10.249.30.105:3000/d/widNk59Mz/netapp-detail-volume?orgId=1&refresh=1m
> feat: supporting new_status metric in native dashboards

- cmd/harvest/harvest.go
> fix: harvest start|restart should not kill processes with poller in name

- README.md
> docs: adding re-import of dashboards info in upgrade case

- cmd/tools/grafana/grafana.go
- cmd/tools/grafana/grafana_test.go
- grafana/prometheus/harvest_dashboard_metadata.json
Same PR as #333, but for the release branch.
> fix: false negatives by prefix matcher (second PR for release branch)

- grafana/prometheus/harvest_dashboard_aggregate.json
> fix(grafana): correcting fill grade graphic change aggr dashboard

- conf/zapi/cdot/9.8.0/disk.yaml
- conf/zapiperf/cdot/9.8.0/disk.yaml
- grafana/dashboards/harvest_dashboard_disk.json
Grafana: http://10.249.25.52:3000/ admin/admin
> feat: disk dashboard changes

- cmd/poller/collector/helpers.go
- cmd/poller/collector/helpers_test.go
> fix: Improve ZAPI template selection

- integration/Jenkinsfile
- integration/test/core/poller.go
- integration/test/harvest.yml
- integration/test/installer/docker.go
- integration/test/installer/harvest.go
- integration/test/installer/installer.go
- integration/test/installer/installerFactory.go
- integration/test/installer/native.go
- integration/test/installer/rpm.go
- integration/test/metric_test.go
- integration/test/native_installer_test.go
- integration/test/rpm_installer_test.go
- integration/test/utils/http_utils.go
- integration/test/utils/utils.go
- jenkins/artifacts/jenkinsfile
- Validate metrics data for each poller that is defined in the harvest
- Jenkinsfile for pipeline
- Adding buildserver agent
> feat: install automation code for RPM and Native tar file.

- pkg/api/ontapi/zapi/system.go
- pkg/api/ontapi/zapi/system_test.go
> fix: improve 7-mode version parsing

- README.md
- cmd/poller/poller.go
- cmd/tools/doctor/doctor_test.go
- harvest.cue
- pkg/conf/conf.go
- pkg/conf/conf/zapiperf/limited1.yaml
- pkg/conf/conf_test.go
- pkg/conf/testdata/conf/zapiperf/limited1.yaml
- pkg/conf/testdata/issue_396.yaml
- pkg/conf/testdata/normal.yaml
> fix: built-in collectors should have overridable config

- integration/Jenkinsfile
- integration/test/docker_installer_test.go
1. Tag docker installer test
2. Update jenkins file to use docker instead of RPM
> feat: update jenkins file and enable docker tests

- grafana/dashboards/harvest_dashboard_aggregate.json
fix for #133 
- corrected titles of 6 graphs
> fix: incorrect titles in aggregate dashboard

- pkg/test/node_test.go
- pkg/test/testdata/custom.yaml
- pkg/test/testdata/default.yaml
- pkg/tree/node/node.go
> feat: templates should be extendable without modifying the original

- integration/Jenkinsfile
- integration/test/docker_installer_test.go
- jenkins/artifacts/JenkinWorkflow
1. update existing jenkins file to pick branch, docker and rpm build
2. create a single workflow jenkins file to quality dev branch for every commit
> feat: jenkins file for qualifying dev branch

- grafana/dashboards/influxdb/harvest_dashboard_aggregate.json
- grafana/dashboards/influxdb/harvest_dashboard_metadata.json
> feat: first 2 dashboards

- autosupport/README.md
- cmd/poller/poller.go
- harvest.yml
> docs: document autosupport

- conf/zapi/7mode/8.6.0/aggr.yaml
- conf/zapi/7mode/8.6.0/disk.yaml
- conf/zapi/7mode/8.6.0/node.yaml
- conf/zapi/7mode/8.6.0/shelf.yaml
- conf/zapi/7mode/8.6.0/status.yaml
- conf/zapi/7mode/8.6.0/subsystem.yaml
- conf/zapi/7mode/8.6.0/volume.yaml
- conf/zapiperf/7mode/8.2.5/cifs_node.yaml
- conf/zapiperf/7mode/8.2.5/fcp.yaml
- conf/zapiperf/7mode/8.2.5/lun.yaml
- conf/zapiperf/7mode/8.2.5/nfsv3_node.yaml
- conf/zapiperf/7mode/8.2.5/nfsv4_node.yaml
- conf/zapiperf/7mode/8.2.5/system_node.yaml
- conf/zapiperf/7mode/8.2.5/volume.yaml
- conf/zapiperf/7mode/8.2.5/volume_node.yaml
- conf/zapiperf/7mode/8.2.5/wafl.yaml
> fix: 7mode dashboard

- integration/Jenkinsfile
- integration/go.mod
- integration/go.sum
- integration/test/dashboard_jsons/harvest_dashboard_disk.json
- integration/test/dashboard_test.go
- integration/test/docker/docker_mgr.go
- integration/test/docker_installer_test.go
- integration/test/grafana/grafana_mgr.go
- integration/test/harvest.yml
- integration/test/installer/docker.go
- integration/test/installer/grafana.go
- integration/test/installer/installerFactory.go
- integration/test/installer/prometheus.go
- integration/test/installer/rpm.go
- integration/test/metric_test.go
- integration/test/native_installer_test.go
- integration/test/prometheus.yml
- integration/test/rpm_installer_test.go
- integration/test/utils/http_utils.go
- integration/test/utils/utils.go
- jenkins/artifacts/JenkinWorkflow
1. Install grafana and prometheus
2. integrate harvest, grafana and prometheus
3. import dashboards
4. validate dashboard details
> feat: add dashboard tests

- cmd/poller/collector/collector.go
- add more logging when connection fails
Fixes #356
> fix: reset collector retryDelay when connection resumes

- cmd/tools/asup/asup.go
- removed fmt.Prints and panics
- removed svm stats since they're not collected
> refactor: clean-up autosupport logging

- cmd/collectors/zapi/plugins/shelf/shelf.go
- cmd/exporters/influxdb/influxdb_test.go
- cmd/exporters/prometheus/prometheus.go
- cmd/poller/collector/collector.go
- cmd/poller/exporter/exporter.go
- cmd/poller/plugin/aggregator/aggregator_test.go
- cmd/poller/plugin/label_agent/label_agent_test.go
- cmd/poller/poller.go
- pkg/matrix/matrix.go
- pkg/matrix/matrix_test.go
> fix: metrics overwrite problem

- grafana/dashboards/harvest_dashboard_volume_details.json
> fix: remove "Per Volume IO Density"

- grafana/dashboards/harvest_dashboard_svm_details.json
Thanks to Jeff Asher for sharing!
> feat: svm details dashboard

- grafana/dashboards/harvest_dashboard_cluster.json
> fix: chart name correction in cluster dashboard

- CHANGELOG.md
See [internal](https://github.com/NetApp/harvest-private/wiki/21.08.0-commits) for commits
> docs: update changelog for 21.08

- conf/zapiperf/7mode/8.2.5/nic_common.yaml
- conf/zapiperf/cdot/9.8.0/nic_common.yaml
- grafana/dashboards/harvest_dashboard_network.json
- grafana/dashboards/harvest_dashboard_network_detail.json
- grafana/dashboards/harvest_dashboard_nvme_fc.json
> fix: absent metric nic_state used in dashboards

- cmd/collectors/zapiperf/zapiperf.go
> fix: process deprecated counters when there are no replacements

- integration/Jenkinsfile
- integration/test/copy_logs_test.go
- integration/test/docker/docker_mgr.go
- integration/test/installer/docker.go
- integration/test/installer/install_utils.go
- integration/test/installer/native.go
- integration/test/installer/rpm.go
- jenkins/artifacts/jenkinsfile
1. Add a script to uninstall all type of harvest before start of installation
2. update jenkins pipeline to copy logs and save it 
3. print node ip inside setup block for user to debug test failures
4. code refactor
> feat: add slave ip address and uninstall

- integration/test/dashboard_test.go
- jenkins/artifacts/jenkinsfile
1. Add test for seven mode dashboards
2. add delay before getting response from grafana
3. refactor test code
> fix: fix dashboard test failures due to 7mode changes

- pkg/test/node_test.go
> refactor: make test code more readable

- cmd/poller/poller.go
- cmd/poller/poller_test.go
> fix: poller should parse busybox ping

- jenkins/artifacts/jenkinsfile
1. Ignore status check updates for PR-xxx jobs
> feat: workaround for ignoring PR-xxx jobs

- README.md
- harvest.cue
Update harvest.cue with label sets
> docs: Harvest should support label sets

- integration/Jenkinsfile
- jenkins/artifacts/jenkinsfile
1. cleanup all docker images 
2. cleanup /opt/home/nightly
> fix: remove clean up docker images and artifacts to free up space

- conf/README.md
> docs: sensor docs need to match product

- integration/Jenkinsfile
- integration/test/dashboard/data_validation.go
- integration/test/dashboard_json_test.go
- jenkins/artifacts/jenkinsfile
1. increase timeouts
2. remove used/unused containers/images and volumes
> fix: delete running docker containers and fix counter test

- README.md
- cmd/tools/generate/generate.go
- service/contrib/README.md
- service/contrib/target.tmpl
> feat: improve instantiated systemd template

- cmd/tools/grafana/grafana.go
- integration/go.mod
- integration/go.sum
- integration/test/dashboard/data_validation.go
- integration/test/dashboard_test.go
1. read folder names from dashboard yaml files
> ci: use folder names from the dashboard yamls

- jenkins/artifacts/jenkinsfile
1. Replace github check with webhook
> ci: replace github check with notification

- docs/AuthAndPermissions.md
- docs/samples/openssl.cnf
- harvest.yml
- pkg/api/ontapi/zapi/client.go
- pkg/conf/conf.go
docs: document how to create self-signed SAN certificates
Fixes #686
> feat: certificate_auth should work with SAN certificates

- service/admin-node/README.md
- service/contrib/README.md
Reported and fixed by @mamoep on Slack
> fix: systemd harvest instances should wait for network

- cmd/poller/collector/helpers.go
- cmd/poller/plugin/README.md
- cmd/poller/plugin/label_agent/parse_rules.go
- cmd/tools/doctor/doctor.go
- conf/rest/9.13.0/volume.yaml
- conf/zapi/7mode/8.6.0/shelf.yaml
- conf/zapi/cdot/9.8.0/shelf.yaml
- conf/zapi/cdot/9.8.0/volume.yaml
- pkg/test/mergeTemplates/21.08.0_lun_merge_21.08.0_extended.yaml
- pkg/test/mergeTemplates/lun_merge_21.08.0_extended.yaml
- pkg/test/node_test.go
- pkg/test/preProcessResultData/p_21.08.0_extend_lun.yaml
- pkg/test/testdata/21.08.0_extend_lun.yaml
- pkg/tree/tree.go
- pkg/tree/yaml/yaml.go
> fix: improve template yaml parsing

- cmd/collectors/zapi/collector/zapi.go
- cmd/collectors/zapiperf/plugins/vscan/vscan.go
- cmd/collectors/zapiperf/zapiperf.go
- cmd/exporters/prometheus/prometheus.go
- conf/zapiperf/cdot/9.8.0/vscan.yaml
- conf/zapiperf/cdot/9.8.0/vscan_svm.yaml
- conf/zapiperf/default.yaml
> feat: add antivirus counters vscan

- grafana/dashboards/cmode/harvest_dashboard_snapmirror.json
> fix: snapmirror dashboard fix

- CHANGELOG.md
- cmd/admin/auth.go
- harvest.yml
- jenkins/artifacts/jenkinsfile
> feat: admin cert path change

- grafana/dashboards/cmode/harvest_dashboard_volume.json
- grafana/dashboards/cmode/harvest_dashboard_volume_details.json
> fix: volume dash fix

- grafana/dashboards/cmode/harvest_dashboard_mcc_cluster.json
- integration/test/data/counter_data.go
- integration/test/installer/grafana.go
1. Add path object metrics for mcc
> feat: add path object metrics into mcc dash

- cmd/collectors/zapi/plugins/quota/quota.go
- cmd/poller/plugin/aggregator/aggregator.go
- cmd/poller/plugin/label_agent/label_agent.go
- cmd/poller/plugin/label_agent/label_agent_test.go
- cmd/poller/plugin/label_agent/parse_rules.go
- cmd/poller/plugin/test/plugin_test.go
- cmd/poller/plugin/test/testdata/sample.yaml
> feat: plugin ordering

- integration/Jenkinsfile
add env variable to keep pollers in running state.
> ci: prevent poller being killed after run

- cmd/collectors/zapi/plugins/quota/quota.go
- conf/zapi/7mode/8.6.0/qtree.yaml
Qtree metrics:
Quota testing is pending.
7mode clusters don't have any quota created, I am trying to create the quota and see the quota metrics are populated or not.
> feat: adding qtree template for 7mode

- cmd/exporters/prometheus/prometheus.go
- pkg/conf/conf.go
> feat: Prometheus exporter should offer option to sort labels

- cmd/exporters/prometheus/README.md
> docs: document Prometheus sort_labels option

- cmd/poller/plugin/README.md
- cmd/poller/plugin/label_agent/label_agent.go
- cmd/poller/plugin/label_agent/label_agent_test.go
- cmd/poller/plugin/label_agent/parse_rules.go
- conf/rest/9.13.0/aggr.yaml
- conf/rest/9.13.0/qtree.yaml
- conf/rest/9.13.0/quota.yaml
- conf/rest/9.13.0/shelf.yaml
- conf/rest/default.yaml
- conf/zapi/cdot/9.8.0/aggr.yaml
covered the changes from 775 PR. 
6 aggr fields:
aggr_snapshot_maxfiles_possible rejected --> Done
aggr_hybrid_cache_size_total -> Done
aggr_raid_plex_count -> Done
aggr_snapshot_inode_used_percent rejected
aggr_space_used_percent rejected 
aggr_space_reserved -> rejected
Qtree and Shelf, basic template changes are ready, plugin will be next.
> feat: rest gaps aggr, qtree, shelf

- cmd/poller/collector/collector.go
- cmd/poller/schedule/schedule.go
> feat: task recovery handling

- cmd/tools/doctor/restZapiDiff.go
some keys may not be unique. For now going with assumption that they will most likely be unique.
Current Diff as blow
################## Metrics Diffs in prometheus ##############
volume_space_physical_used test123 2.465792e+06 -> 2.473984e+06
volume_space_physical_used FlexGroup_Infinity 2.79736098816e+11 -> 2.7973607424e+11
volume_space_physical_used backup_new 3.1019393024e+10 -> 3.1019384832e+10
volume_space_physical_used backup_test 6.264803328e+09 -> 6.264795136e+09
aggr_space_used_percent aggr3 98 -> 95
aggr_space_used_percent aggr4 24 -> 21
aggr_space_used_percent aggr1 66 -> 64
aggr_space_used_percent aggr2 76 -> 71
snapmirror_newest_snapshot_timestamp c6bfbce6-8735-11eb-a5eb-00a098e0060e 1.6430475e+09 -> 0
snapmirror_newest_snapshot_timestamp f535efc6-8735-11eb-a5eb-00a098e0060e …
> feat: value diff rest vs zapi metric

- cmd/collectors/zapiperf/zapiperf.go
> feat: duplicate counter error in workload_detail_volume

- grafana/dashboards/cmode/harvest_dashboard_svm_details.json
> fix: remove redundant and misplaced panel from SVM details dashboard

- cmd/tools/grafana/grafana.go
- integration/Jenkinsfile
- integration/test/dashboard_test.go
- integration/test/test.sh
- jenkins/artifacts/jenkinsfile
> feat: grafana dashboards should match release version

- cmd/tools/grafana/grafana.go
fix for dashboard import when dashboard id is not null.
> fix: id issue in grafana import/export

- cmd/tools/grafana/grafana.go
- cmd/tools/grafana/grafana_test.go
> fix: relax Grafana version check constraint

- cmd/collectors/rest/rest.go
```
9:14PM WRN goharvest2/cmd/collectors/rest/rest.go:406 > Instance not found Instance key=7729a4c8-3a14-4104-8559-acbe760f885a Poller=cluster-07 collector=Rest:Volume
9:14PM WRN goharvest2/cmd/collectors/rest/rest.go:406 > Instance not found Instance key=b0997192-c7cc-46e1-8efb-b6d485a0ecd8 Poller=cluster-07 collector=Rest:Volume
```
> fix: instance creation issue rest

- cmd/tools/generate/generate.go
- docker/onePollerPerContainer/docker-compose.tmpl
> feat: cert dir for admin

- cmd/poller/collector/helpers.go
- cmd/tools/doctor/doctor.go
- pkg/tree/tree.go
> fix: poller should not panic when template is invalid or empty

- cmd/collectors/rest/rest.go
- cmd/collectors/rest/templating.go
- cmd/collectors/zapi/collector/zapi.go
- cmd/poller/collector/helpers.go
- conf/rest/9.12.0/snapshotPolicy.yaml
- conf/rest/default.yaml
- conf/zapi/cdot/9.8.0/snapshotPolicy.yaml
- conf/zapi/default.yaml
- grafana/dashboards/cmode/harvest_dashboard_data_protection.json
- pkg/errors/errors.go
> fix: rename snapshot.yaml to snapshotPolicy.yaml

- jenkins/artifacts/jenkinsfile
> feat: jfrog docker integration

- cmd/collectors/zapi/collector/zapi.go
> fix: zapi Collector batch size issue

- cmd/tools/grafana/grafana.go
- grafana/dashboards/cmode/harvest_dashboard_volume_details.json
- integration/test/dashboard_test.go
Fixes #815
fix: remove unimplemented "Fabricpool Drilldown" panel
> feat: grafana dashboards should support multi-select variables

- docs/AuthAndPermissions.md
> docs: include 7-mode cli role commands

- grafana/dashboards/cmode/harvest_dashboard_qtree.json
- integration/test/dashboard_test.go
This supports ```Related Dashboards```
> feat: qtree dashboard 1.6 parity

- conf/rest/9.12.0/node.yaml
> feat: REST collector should collect the node cpu-busytime metric

- pkg/util/util.go
as reported by Dan Butler on Slack
Verified on
> feat: harvest status should run on systems without pgrep

- conf/zapi/cdot/9.8.0/aggr_efficiency.yaml
- conf/zapi/default.yaml
- grafana/dashboards/cmode/harvest_dashboard_cluster.json
- integration/test/data/counter_data.go
> feat: Harvest should include storage efficiency

- grafana/dashboards/cmode/harvest_dashboard_data_protection.json
- grafana/dashboards/cmode/harvest_dashboard_data_protection_snapmirror.json
Issue: few tables and panels were show UI errors as it's showing older data
Fix: Changed to instant=true as all tables and panels would need latest data to show in dashboards
> fix: data protection fix to add instant in panels

- grafana/dashboards/cmode/harvest_dashboard_cluster.json
- grafana/dashboards/cmode/harvest_dashboard_shelf.json
> feat: power changes to cluster and shelve dashboard

- grafana/dashboards/cmode/harvest_dashboard_svm_details.json
> feat: include antivirus counters in SVM dashboard / CIFS drill-down

- conf/rest/9.12.0/snapmirror.yaml
```
hardikl@hardikl-mac-0 harvest % curl -k -uadmin:umengqa890! 'https://10.231.84.110/api/private/cli/snapmirror?fields=status,type,relationship_type' | grep status
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0      "status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": "idle",
"status": …
```
> fix: snapmirror rest gap labels

- cmd/collectors/unix/main.go
- cmd/collectors/unix/process.go
- cmd/harvest/harvest.go
- pkg/util/util.go
* improve poller status on Mac
> feat: Replace ps usage with psutil

- cmd/poller/collector/collector.go
- cmd/poller/exporter/exporter.go
- cmd/poller/plugin/aggregator/aggregator_test.go
- cmd/poller/plugin/label_agent/label_agent_test.go
- cmd/poller/plugin/plugin.go
- cmd/poller/plugin/test/plugin_test.go
- cmd/poller/poller.go
- cmd/tools/rest/client.go
- pkg/api/ontapi/zapi/client.go
- pkg/logging/logger.go
> feat: plugin loggers should include object Name

- grafana/dashboards/cmode/harvest_dashboard_nfs4storePool_detail.json
Thanks to Rusty Brown for reporting
> fix(grafana): StorePool legend should read CopyStateAlloc

- grafana/dashboards/7mode/harvest_dashboard_disk7.json
- grafana/dashboards/cmode/harvest_dashboard_disk.json
> fix: disk dashboard has wrong units for two panels

- grafana/dashboards/cmode/harvest_dashboard_qtree.json
Add two new panels for total_ops and internal_ops
Thanks to @mamoep for the contribution!
Fixes #1079
> feat: add qtree variable to qtree dashboard

- cmd/collectors/restperf/plugins/fcp/fcp.go
- cmd/collectors/restperf/plugins/headroom/headroom.go
- cmd/collectors/restperf/plugins/nic/nic.go
- cmd/collectors/restperf/plugins/volume/volume.go
- cmd/collectors/restperf/restperf.go
- conf/restperf/9.12.0/fcp.yaml
- conf/restperf/9.12.0/nic_common.yaml
- conf/restperf/9.12.0/resource_headroom_aggr.yaml
- conf/restperf/9.12.0/volume.yaml
Pending plugin vscan. It will be developed once templates are ready. Pending from Ontap side.
> feat: restperf plugins

- grafana/dashboards/7mode/harvest_dashboard_disk7.json
- grafana/dashboards/cmode/harvest_dashboard_disk.json
> fix: add description in Disk dashboard panels

- cmd/poller/plugin/aggregator/aggregator.go
- cmd/poller/plugin/label_agent/label_agent.go
- cmd/poller/plugin/label_agent/parse_rules.go
- cmd/poller/plugin/metric_agent/metric_agent.go
- cmd/poller/plugin/metric_agent/parse_rules.go
> fix: rename generic receivers

- cmd/exporters/prometheus/prometheus.go
> fix: Prometheus exporter should escape label_value

- cmd/tools/grafana/grafana.go
> fix: fix grafana version get call

- cmd/collectors/restperf/restperf.go
- conf/restperf/9.12.0/fcp.yaml
- conf/restperf/9.12.0/fcp_lif.yaml
- conf/restperf/9.12.0/workload_detail.yaml
- conf/restperf/9.12.0/workload_detail_volume.yaml
Add support for adding metric as label
fix for workload_detail
fcp rest gaps
> feat: restperf gap fill

- cmd/collectors/rest/plugins/quotareport/quotaReport.go
- cmd/collectors/rest/rest.go
- cmd/collectors/zapi/collector/zapi.go
- cmd/collectors/zapi/plugins/quotaReport/quotaReport.go
- cmd/collectors/zapi/plugins/quotareport/quotaReport.go
- conf/rest/9.12.0/quotaReport.yaml
- conf/rest/default.yaml
- conf/zapi/cdot/9.8.0/quotaReport.yaml
- conf/zapi/default.yaml
- grafana/dashboards/cmode/harvest_dashboard_quotaReport.json
> feat: quota dashboard

- cmd/collectors/restperf/restperf.go
- cmd/collectors/zapiperf/zapiperf.go
- pkg/matrix/metric.go
- pkg/matrix/metric_float64.go
9:31PM WRN matrix/metric_float64.go:235 > Negative counter detected Poller=u2 collector=ZapiPerf:NFSv3 metric=read_avg_latency minuend=303902176895 subtrahend=303902188591
> fix: negative counter values

- grafana/dashboards/cmode/harvest_dashboard_cluster.json
> feat: add node cpu busy to cluster dashboard

- conf/rest/9.12.0/netConnections.yaml
- conf/rest/default.yaml
> feat: add net connections template for Rest Collector

- go.mod
- go.sum
- vendor/golang.org/x/text/internal/language/language.go
- vendor/golang.org/x/text/internal/language/parse.go
- vendor/golang.org/x/text/language/parse.go
- vendor/modules.txt
See https://pkg.go.dev/vuln/GO-2021-0113
> fix: govulncheck scan issue GO-2021-0113

- grafana/dashboards/7mode/harvest_dashboard_aggregate7.json
- grafana/dashboards/7mode/harvest_dashboard_cluster7.json
- grafana/dashboards/7mode/harvest_dashboard_disk7.json
- grafana/dashboards/7mode/harvest_dashboard_lun7.json
- grafana/dashboards/7mode/harvest_dashboard_network7.json
- grafana/dashboards/7mode/harvest_dashboard_node7.json
- grafana/dashboards/7mode/harvest_dashboard_nvme_fc7.json
- grafana/dashboards/7mode/harvest_dashboard_shelf7.json
- grafana/dashboards/7mode/harvest_dashboard_volume7.json
- grafana/dashboards/cmode/harvest_dashboard_aggregate.json
- grafana/dashboards/cmode/harvest_dashboard_cluster.json
- grafana/dashboards/cmode/harvest_dashboard_compliance.json
- grafana/dashboards/cmode/harvest_dashboard_data_protection_snapshot.json
- grafana/dashboards/cmode/harvest_dashboard_disk.json
- grafana/dashboards/cmode/harvest_dashboard_headroom.json
- grafana/dashboards/cmode/harvest_dashboard_lun.json
- grafana/dashboards/cmode/harvest_dashboard_mcc_cluster.json
- grafana/dashboards/cmode/harvest_dashboard_metadata.json
- grafana/dashboards/cmode/harvest_dashboard_network_detail.json
- grafana/dashboards/cmode/harvest_dashboard_nfs4storePool_detail.json
- grafana/dashboards/cmode/harvest_dashboard_node_details.json
- grafana/dashboards/cmode/harvest_dashboard_nvme_fc.json
- grafana/dashboards/cmode/harvest_dashboard_power.json
- grafana/dashboards/cmode/harvest_dashboard_qtree.json
- grafana/dashboards/cmode/harvest_dashboard_quotaReport.json
- grafana/dashboards/cmode/harvest_dashboard_security.json
- grafana/dashboards/cmode/harvest_dashboard_shelf.json
- grafana/dashboards/cmode/harvest_dashboard_snapmirror.json
- grafana/dashboards/cmode/harvest_dashboard_svm_details.json
- grafana/dashboards/cmode/harvest_dashboard_volume_details.json
> feat: add Grafana tags on default dashboards

- conf/rest/9.7.0/nfs_clients.yaml
- conf/rest/default.yaml
- grafana/dashboards/cmode/harvest_dashboard_nfs_clients.json
- integration/test/dashboard_test.go
- integration/test/data/counter_data.go
> feat: rest nfs connections dashboard

- grafana/dashboards/cmode/harvest_dashboard_headroom.json
Thanks to Rusty Brown for contributing!
> feat: add available ops to headroom dashboard

- conf/restperf/9.12.0/cifs_node.yaml
- conf/zapiperf/cdot/9.8.0/cifs_node.yaml
- grafana/dashboards/cmode/harvest_dashboard_cdot.json
- integration/test/dashboard_test.go
Incorporated the panels outlined here: https://grafana.com/grafana/dashboards/10181-netapp-overview/
> feat: Solution based Cdot dashboard

- .github/workflows/golangci-lint.yml
See also https://github.com/golangci/golangci-lint-action/issues/297
> chore: increase golangci-lint timeout

- cmd/poller/poller.go
- cmd/poller/poller_test.go
test: add tests for 9.11, 9.12, and 9.13
> feat: Harvest should use REST unconditionally starting with 9.13.1

- cmd/collectors/rest/rest.go
instances should not be removed based on the endpoint api call's records.
> fix: svm records count

- conf/rest/9.12.0/svm.yaml
> fix: svm with private cli

- cmd/collectors/storagegrid/storagegrid.go
- cmd/exporters/prometheus/httpd.go
- cmd/exporters/prometheus/prometheus.go
- conf/storagegrid/11.6.0/tenant.yaml
fix: Prometheus should dedup labels
fix: storagegrid metrics should include tenant
> fix: storagegrid collector should use metadata collection

- conf/rest/9.12.0/netPort.yaml
- conf/zapi/cdot/9.8.0/netPort.yaml
> fix: net port template fix

- docs/prepare-fsx-clusters.md
- grafana/dashboards/cmode/compliance.json
- grafana/dashboards/cmode/data_protection_snapshot.json
- grafana/dashboards/cmode/security.json
- grafana/dashboards/cmode/svm.json
- grafana/dashboards/cmode/volume.json
> feat: tag fsx dashboards

- grafana/dashboards/cmode/svm.json
> fix: svm copy panel fix

- conf/rest/default.yaml
- conf/restperf/default.yaml
- docs/configure-rest.md
- make links relative which makes GoLand happy
- reformat
- shorten example
- simplify rest templates schedule durations
> docs: add rest/restperf collector docs

- README.md
> ci: test tag closed issues with `status/testme`

- cmd/collectors/rest/plugins/qtree/qtree.go
- cmd/collectors/rest/plugins/shelf/shelf.go
- cmd/collectors/rest/rest.go
- cmd/collectors/restperf/restperf.go
- cmd/collectors/simple/simple.go
- cmd/collectors/storagegrid/storagegrid.go
- cmd/collectors/unix/main.go
- cmd/collectors/zapi/collector/parsers.go
- cmd/collectors/zapi/plugins/qtree/qtree.go
- cmd/collectors/zapi/plugins/sensor/sensor.go
- cmd/collectors/zapi/plugins/shelf/shelf.go
- cmd/collectors/zapiperf/zapiperf.go
- cmd/poller/plugin/metricagent/metric_agent.go
- conf/rest/9.10.0/aggr.yaml
- conf/rest/9.12.0/aggr.yaml
- conf/rest/9.12.0/volume.yaml
- conf/zapi/cdot/9.8.0/volume.yaml
- docs/plugins.md
- pkg/matrix/matrix.go
- pkg/matrix/metric.go
feat: add metric_agent percent operation
docs: add metric_agent percent operation to docs
> feat: plugins can use raw or display metric in calculations

- grafana/dashboards/cmode/volume.json
Fixes: #1535
Thanks to @Falcon667 for raising
> feat: include inodes file usage in volume dashboard

- grafana/dashboards/cmode/svm.json
Panels Detail:
**FCP Drilldown** -> Changes in 2 panels
**ISCSI Drilldown** -> Changes in 2 panels
**NFSv3 Front Drilldown** -> Changes in 3 panels
**NFSv4 Drilldown** -> Changes in 3 panels
**NFSv4.1 Drilldown** -> Changes in 3 panels
> feat: topk support in svm dashboard - 2

- cmd/collectors/rest/rest.go
- cmd/collectors/zapi/collector/zapi.go
- pkg/matrix/instance.go
> fix: label not cleared when it is not available in subsequent zapi/rest poll

- grafana/dashboards/7mode.yml
- grafana/dashboards/cdot.yml
- grafana/dashboards/storageGrid.yml
> feat: include storagegrid dashboard in docker compose

- cmd/poller/poller.go
- cmd/poller/poller_test.go
When HARVEST_NO_UPGRADE ENVVAR is set, detect if ZAPIs are supported by cluster. If they are, honor ENVVAR, otherwise use REST.
Fixes: #1516
> feat: honor HARVEST_NO_UPGRADE ENVVAR when ZAPI exist

- cmd/collectors/rest/plugins/securityaccount/securityaccount.go
- cmd/collectors/rest/rest.go
- conf/rest/9.12.0/security_account.yaml
Parse applications and then created 1-1 mapping between application and methods. 
Now, ZAPI and REST would have same behaviour.
Fix: Handling this, need to call extra rest call in plugin.
> fix: handling array of array in rest security accounts

- cmd/tools/grafana/dashboard_test.go
- grafana/dashboards/storagegrid/overview.json
- grafana/dashboards/storagegrid/tenant.json
- harvest.yml
test: add unit test to ensure variable exists
> fix: variable DS_PROMETHEUS should exist in dashboard

- cmd/tools/grafana/dashboard_test.go
- conf/zapiperf/cdot/9.8.0/nfsv3.yaml
- grafana/dashboards/cmode/svm.json
- integration/test/dashboard_json_test.go
- integration/test/data/counter_data.go
Add for v4 after more soak time with v3 heatmap
> feat: add nfsv3 latency heatmap

- cmd/tools/generate/generate.go
> fix: port in generate docker command should work for standlone harvest container deployment

- grafana/dashboards/cmode/node.json
> fix: panel name alias

- grafana/dashboards/cmode/shelf.json
Fixes #1727
removed rpm color coding as well. like we did for power dashboard
> feat: shelf power panel alignment issue

- grafana/dashboards/cmode/svm.json
> fix: svm dashboard stat panels aggregation

- grafana/dashboards/cmode/snapmirror.json
> fix: changed filter from not nil to greater than 0

- cmd/exporters/influxdb/influxdb_test.go
- cmd/poller/exporter/exporter.go
- cmd/poller/poller.go
> feat: add datacenter to metadata exporter_time metrics

- cmd/tools/grafana/dashboard_test.go
- cmd/tools/grafana/units.yaml
- grafana/dashboards/cmode/qtree.json
Thanks to Watson9121 for raising
> feat: qtree dashboard should include topK qtrees by disk used growth

- cmd/collectors/rest/rest.go
- cmd/collectors/storagegrid/rest/client.go
- cmd/poller/poller.go
- cmd/tools/generate/generate.go
- cmd/tools/rest/client.go
- cmd/tools/rest/rest.go
- cmd/tools/rest/swag.go
- cmd/tools/zapi/zapi.go
- pkg/api/ontapi/zapi/client.go
- pkg/api/ontapi/zapi/client_test.go
- pkg/auth/auth.go
- pkg/conf/conf.go
> feat: Harvest should fetch auth via script

- grafana/dashboards/cmode/smb2.json
> fix: Session Setup Latency Heatmap panel is duplicate on the dashboard

- grafana/dashboards/cmode/fsa.json
> docs: update FSA dashboard information

- docs/prepare-cdot-clusters.md
Thanks to Watson9121 for raising
> docs: add permissions to docs for qos

- grafana/dashboards/cmode/aggregate.json
> fix: adding available column in aggr dashboard

- cmd/collectors/ems/ems.go
Testing is in-progress with the vsim.
> fix: log time drift between nodes in ems collector

- cmd/tools/template/template_test.go
- conf/rest/9.8.0/cifs_clients.yaml
- conf/rest/default.yaml
- conf/zapi/cdot/9.8.0/cifs_clients.yaml
- conf/zapi/default.yaml
Fixes: #1826
```bash
curl -s http://localhost:12990/metrics | rg -v "#|metadata_" | sort | prom
cifs_clients_labels{
client_ip = "10.249.154.33",
client_port = "50322",
cluster = "ocum-infinity",
datacenter = "nane1",
identifier = "153417359",
network_context_id = "9",
node = "ocum-infinity-01",
server_ip = "10.231.176.184",
svm = "vs1_nfs_cifs",
} 1.0
```
> feat: Harvest should collect CIFS clients

- docs/monitor-harvest.md
- mkdocs.yml
> doc: document metadata metrics Harvest publishes

- container/prometheus/prometheus.yml
> feat: update docker prometheus variables

- docs/dashboards.md
Thanks to DietmarE for reporting!
> doc: fix grafana spelling

- CHANGELOG.md
- pkg/changelog/main.go
refactor: changelog generator should categorize `doc` prs
> doc: changelog for 23.05

- .github/workflows/go.yml
- docs/configure-harvest-basic.md
- integration/Jenkinsfile
- jenkins/artifacts/jenkinsfile
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/testdata/get_pass
doc: clarify credentials_script docs
Fixes #2127
> fix: Harvest should always pass `addr` argument to credentials_script

- cmd/tools/grafana/dashboard_test.go
- cmd/tools/grafana/metrics.go
- grafana/dashboards/cmode/network.json
- grafana/dashboards/cmode/node.json
- grafana/dashboards/cmode/qtree.json
- grafana/dashboards/cmode/s3ObjectStorage.json
- grafana/dashboards/cmode/svm.json
- grafana/dashboards/storagegrid/overview.json
Prior the changes:
Now with changes:
> feat: Supporting topk in S3 dashboard

- cmd/tools/generate/counter.go
- cmd/tools/generate/counter.yaml
- conf/zapiperf/cdot/9.8.0/fcvi.yaml
- docs/ontap-metrics.md
> feat: update ONTAP metric document

- conf/rest/9.12.0/node.yaml
- conf/zapi/cdot/9.8.0/node.yaml
- grafana/dashboards/cmode/cluster.json
Details [here](https://discord.com/channels/855068651522490400/1125413118210756698/1126395941965017178)
> feat: add cpu_firmware_release to Cluster dashboard

- grafana/dashboards/cmode/volume.json
> feat: add volume other latency to volume dashboard

- grafana/dashboards/cmode/svm.json
> fix: renaming nfs panels in svm dashboard

- container/onePollerPerContainer/docker-compose.tmpl
- prom-stack.tmpl
[Reference](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-1)
> fix: add quotes for ports in docker compose files

- cmd/tools/rest/client.go
- pkg/matrix/matrix.go
This is very minor hence no profiling is done.
> perf: Rest client allocs improvements

- pkg/matrix/matrix.go
> fix: sg collector throws NPE

- conf/rest/9.12.0/lif.yaml
- conf/zapi/cdot/9.8.0/lif.yaml
> fix: lif template should use unique instanceKeys

- CHANGELOG.md
doc: release notes for 23.11
Pending:
1: Multi Conf Story
2: Any Burt we want to highlight?
> doc: release notes for 23.11

- cmd/poller/plugin/labelagent/label_agent_test.go
- conf/rest/9.12.0/lun.yaml
- conf/restperf/9.12.0/lun.yaml
- conf/zapi/cdot/9.8.0/lun.yaml
- conf/zapiperf/cdot/9.8.0/lun.yaml
> fix: Harvest should collect luns in qtress

- cmd/tools/rest/rest.go
bin/harvest rest -p dc-1 show data --api svm/svms1   
failed to fetch data err: poller=dc-1 error making request StatusCode: 404, Message: API not found, Code: 3, API: /api/svm/svms1?fields=%2A&return_records=true
**null**
> fix: print results if not nil for rest CLI

- cmd/collectors/rest/plugins/health/health.go
- grafana/dashboards/cmode/health.json
- integration/test/dashboard_json_test.go
> feat: add HA down and sensor issues in Health Dashboard

- cmd/collectors/storagegrid/storagegrid.go
- docs/configure-storagegrid.md
> fix: StorageGRID collectors should support only_cluster_instance

- cmd/collectors/zapi/plugins/shelf/shelf.go
Instead of generating new Matrix for new instances in go plugin, Updating the `data` Matrix itself with extra instances generated from plugin, So that `Label_agent` plugin can be applied as is.
> fix: handling shelf_new_status for 7mode

- grafana/dashboards/cmode/aggregate.json
- grafana/dashboards/cmode/cluster.json
**Previous:**
**With Changes:**
**System Manager For reference:**
> refactor: Update Aggr dashboard to sync with SM

- grafana/dashboards/cmode/svm.json
- grafana/dashboards/cmode/volume.json
> feat: adding per volume panels in SVM dashboard

- cmd/tools/grafana/dashboard_test.go
- grafana/dashboards/cmode/disk.json
- grafana/dashboards/cmode/flexcache.json
- grafana/dashboards/cmode/flexgroup.json
- grafana/dashboards/cmode/fsa.json
- grafana/dashboards/cmode/headroom.json
- grafana/dashboards/cmode/lun.json
- grafana/dashboards/cmode/mcc_cluster.json
- grafana/dashboards/cmode/network.json
- grafana/dashboards/cmode/nfs4storePool.json
- grafana/dashboards/cmode/nfs_clients.json
- grafana/dashboards/cmode/node.json
- grafana/dashboards/cmode/volume.json
- grafana/dashboards/cmode/workload.json
- grafana/dashboards/storagegrid/fabricpool.json
- grafana/dashboards/storagegrid/overview.json
> feat: Harvest dashboards should include an All option

- pkg/conf/conf.go
- pkg/conf/conf_test.go
- pkg/conf/testdata/pollerFiles/empty_poller.yml
> fix: Harvest should not panic when a poller has no config

- grafana/dashboards/cmode/network.json
Thanks to Rusty Brown for contributing this panel.
> feat: Harvest network dashboard should show ethernet errors

- conf/rest/9.12.0/node.yaml
- integration/test/counter_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Fix for these logs in CI tests
> refactor: changed field to use # to handle counter testcase

- cmd/collectors/storagegrid/rest/client.go
Thanks to @ybizeul for reporting!
> fix: Harvest should support poller names with spaces in their names

- grafana/dashboards/cmode/node.json
Thanks to [summertony15](https://github.com/summertony15) for reporting in #2785
> fix: Node dashboard, BMC column should have string unit

- grafana/dashboards/cmode/svm.json
> feat: Harvest SVM dashboard should include NFSv4.2 panels

- grafana/dashboards/cmode/cdot.json
> feat: cDot dashboards work with FSx

- grafana/dashboards/cmode/metadata.json
> feat: add failed collectors stats in metadata dashboard

- cmd/collectors/power.go
when talking to clusters that do not support REST
Seen on `0.74`
{"level":"error","Poller":"F2240-127-26","collector":"Zapi:Sensor","stack":"goroutine 1 [running]:\ngithub.com/netapp/harvest/v2/pkg/logging.MarshalStack({0xc5f340?, 0xc0002b35e0?})\n\tgithub.com/netapp/harvest/v2/pkg/logging/logger.go:157 +0x85\ngithub.com/rs/zerolog.(*Event).Err(0xc000402770, {0xc5f340, 0xc0002b35e0})\n\tgithub.com/rs/zerolog@v1.33.0/event.go:395 +0x51\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).LoadPlugins(0xc000698410, 0xc000676900, {0xc681a0, 0xc0006a13b0}, {0xc0003a42d8, 0x6})\n\tgithub.com/netapp/harvest/v2/cmd/poller/collector/collector.go:716 +0x914\ngithub.com/netapp/harvest/v2/cmd/poller/collector.Init({0xc681a0, …
> fix: power plugin should not fail

- grafana/dashboards/cmode/workload.json
Thanks Rusty Brown for raising on [discord](https://discord.com/channels/855068651522490400/1247534582832566312/1253354291192922215).
> fix: use avg_over_time for qos used %

- cmd/collectors/storagegrid/storagegrid.go
- cmd/exporters/prometheus/prometheus.go
- cmd/exporters/prometheus/prometheus_test.go
- cmd/tools/template/template.go
- conf/storagegrid/11.6.0/storagegrid_metrics.yaml
- pkg/conf/conf.go
Thanks to @Bhagyasri-Dolly for raising!
Fixes: #3021
> feat: Harvest should allow exporting metrics without a prefix

- cmd/tools/grafana/units.yaml
- grafana/dashboards/cmode/quotaReport.json
> fix: Quota dashboard should use kibibytes instead of kilobytes

- grafana/dashboards/cmode/vscan.json
As reported by roller here
https://discord.com/channels/855068651522490400/1275706095494631434/1280109797240213537
> fix: vscan panels throws 422 error

- cmd/tools/grafana/dashboard_test.go
- grafana/dashboards/storagegrid/tenant.json
> feat: Harvest should include time-series panels for tenants and buckets

- cmd/tools/grafana/dashboard_test.go
- grafana/dashboards/cmode-details/volumeBySVM.json
- grafana/dashboards/cmode-details/volumeDeepDive.json
- grafana/dashboards/cmode/aggregate.json
- grafana/dashboards/cmode/data_protection_snapshot.json
- grafana/dashboards/cmode/disk.json
- grafana/dashboards/cmode/external_service_op.json
- grafana/dashboards/cmode/flexgroup.json
- grafana/dashboards/cmode/fsa.json
- grafana/dashboards/cmode/headroom.json
- grafana/dashboards/cmode/lun.json
- grafana/dashboards/cmode/mcc_cluster.json
- grafana/dashboards/cmode/nfsTroubleshooting.json
- grafana/dashboards/cmode/nfs_clients.json
- grafana/dashboards/cmode/qtree.json
- grafana/dashboards/cmode/quotaReport.json
- grafana/dashboards/cmode/s3ObjectStorage.json
- grafana/dashboards/cmode/security.json
- grafana/dashboards/cmode/shelf.json
- grafana/dashboards/cmode/smb.json
- grafana/dashboards/cmode/svm.json
- grafana/dashboards/cmode/volume.json
- grafana/dashboards/cmode/vscan.json
- grafana/dashboards/cmode/workload.json
Thanks to mrgadget_tamu for raising on [Discord](https://discord.com/channels/855068651522490400/1298758081856929842/1298758081856929842).
> fix: update datacenter and cluster variables in dashboards

- grafana/dashboards/cmode/network.json
> fix: correct the mtu unit in network dashboard

- grafana/dashboards/cmode/health.json
> feat: adding the ems doc link in the Health dashboard table

- cmd/collectors/keyperf/keyperf.go
- cmd/collectors/rest/rest.go
- cmd/collectors/rest/rest_test.go
- cmd/tools/rest/rest.go
endpoints still does fetchAll.
> perf: add streaming to Rest collector

- grafana/dashboards/cmode/aggregate.json
- grafana/dashboards/cmode/cdot.json
- grafana/dashboards/cmode/flexgroup.json
- grafana/dashboards/cmode/volume.json
> fix: missing volumes after vol move

- docs/prepare-cdot-clusters.md
Thanks to [cashnmoney](https://discord.com/channels/855068651522490400/1307105652967084132/1313957088766197760) for reporting.
> fix: harvest permissions should include fru

- cmd/collectors/restperf/restperf.go
**Before:**
time=2025-01-03T14:43:07.499+05:30 level=INFO source=collector.go:601 msg=Collected Poller=dc-1 collector=RestPerf:WorkloadDetail apiMs=1386 bytesRx=494906 calcMs=1 exportMs=1 instances=65 instancesExported=65 metrics=795 metricsExported=172 numCalls=3 numPartials=0 parseMs=14 pluginInstances=0 pluginMs=0 pollMs=1674 renderedBytes=33801 skips=1959 zBegin=1735895585824
**After:**
time=2025-01-03T14:41:29.040+05:30 level=INFO source=collector.go:601 msg=Collected Poller=dc-1 collector=RestPerf:WorkloadDetail apiMs=900 bytesRx=303324 calcMs=1 exportMs=1 instances=65 instancesExported=65 metrics=795 metricsExported=172 numCalls=2 numPartials=0 parseMs=9 pluginInstances=0 pluginMs=0 pollMs=1190 renderedBytes=33856 skips=1959 zBegin=1735895487850
> feat: Optimize workload_detail and workload_detail_volume through delay center filter

- grafana/dashboards/cmode/disk.json
Thanks to RobbW. on [Discord](https://discord.com/channels/855068651522490400/1337371899113771071/1337471000526327860) for reporting
> feat: improve CP summary in disk dashboard

- third_party/tidwall/match/match.go
File changes as we run
GOOS=darwin make dev 
Cleaning Harvest files
_  _                     _     ___   __   
| || |__ _ _ ___ _____ __| |_  |_  ) /  \  
| __ / _` | '_\ V / -_|_-<  _|  / / | () | 
|_||_\__,_|_|  \_/\___/__/\__| /___(_)__/  
Formatting
third_party/tidwall/match/match.go
Building
Linting
Govulnchecking
No vulnerabilities found.
No vulnerabilities found.
Deleting AutoSupport binary
> style: format match gjson file

- cmd/collectors/rest/rest_test.go
- cmd/collectors/restperf/restperf_test.go
- cmd/exporters/prometheus/prometheus_test.go
https://go.dev/blog/testing-b-loop
> refactor: Replace benchmark.N with benchmark.Loop()

- grafana/dashboards/cmode/quotaReport.json
> feat: adding space used time series panel in quota dashboard

- cmd/collectors/cisco/cisco.go
- cmd/collectors/cisco/plugins/environment/environment.go
- cmd/collectors/cisco/plugins/networkinterface/networkinterface.go
- cmd/collectors/cisco/plugins/optic/optic.go
- cmd/collectors/cisco/plugins/optic/optic_test.go
- cmd/collectors/cisco/plugins/optic/testdata/N9K-C9336C-FX2_10.3.4-show_interface_transceiver_details.json
- conf/ciscorest/default.yaml
- conf/ciscorest/nxos/9.3.12/interface.yaml
- conf/ciscorest/nxos/9.3.12/optic.yaml
> feat: Cisco collector should collect optics metrics

- cmd/collectors/zapi/plugins/volume/volume.go
- conf/rest/9.12.0/volume.yaml
- conf/rest/9.14.0/volume.yaml
- integration/go.mod
- integration/go.sum
Thanks to Rusty Brown for raising!
> feat: Harvest should collect volume footprint metrics

- conf/keyperf/9.15.0/ethernet_switch_port.yaml
- conf/keyperf/default.yaml
- conf/keyperf/static_counter_definitions.yaml
- conf/rest/9.8.0/ethernet_switch_port.yaml
- conf/rest/default.yaml
- docs/prepare-cdot-clusters.md
Thanks to Robert Watson for reporting!
> feat: Harvest should collect ethernet switch ports

- cmd/collectors/cisco/plugins/environment/environment.go
- cmd/collectors/cisco/plugins/version/version.go
- cmd/collectors/cisco/plugins/version/version_test.go
refactor: better logging when fan speed rows are missing
> fix: improve Cisco RCF parsing

- cmd/collectors/rest/plugins/quota/quota.go
- conf/rest/9.12.0/quota.yaml
prior changes,
```
time=2025-05-15T20:07:55.689+05:30 level=INFO source=collector.go:601 msg=Collected Poller=sarR collector=Rest:Quota apiMs=462 bytesRx=29477 calcMs=0 exportMs=7 instances=45 instancesExported=495 metrics=450 metricsExported=517 numCalls=1 parseMs=2 pluginInstances=0 pluginMs=2 pollMs=466 renderedBytes=117501 zBegin=1747319875216
```
with changes,
```
time=2025-05-15T21:22:22.349+05:30 level=INFO source=collector.go:601 msg=Collected Poller=sarR collector=Rest:Quota apiMs=426 bytesRx=29477 calcMs=0 exportMs=1 instances=45 instancesExported=45 metrics=450 metricsExported=517 numCalls=1 parseMs=2 pluginInstances=0 pluginMs=0 pollMs=428 renderedBytes=121146 zBegin=1747324341920
```
> refactor: update instance generation in quota plugin

- cmd/collectors/rest/plugins/quota/quota.go
- conf/rest/9.12.0/quota.yaml
* refactor: update instance generation in quota plugin
> refactor: update instance generation in quota plugin (#3636)

- docs/prepare-cdot-clusters.md
Thanks to marshit for reporting!
> doc: StatPerf docs should use harvest2 user

- cmd/poller/poller.go
Fixes: #3773
Thanks to @datamuc for reporting
> fix: reduce reason label in metric metadata_component_status

- cmd/tools/generate/counter.yaml
- conf/rest/9.12.0/volume.yaml
- conf/rest/9.14.0/volume.yaml
- conf/zapi/cdot/9.8.0/volume.yaml
- docs/ontap-metrics.md
- grafana/dashboards/cmode/volume.json
> feat: adding volume autosize details in volume dashboard

- cmd/collectors/rest/plugins/cluster/cluster.go
- cmd/collectors/zapi/collector/zapi.go
- cmd/collectors/zapi/plugins/cluster/cluster.go
- conf/zapi/cdot/9.8.0/status.yaml
- docs/ontap-metrics.md
- grafana/dashboards/cmode/datacenter.json
Thanks to Ed Barron for raising!
> feat: Datacenter dashboard should include links to System Manager

- conf/rest/9.16.0/storage_unit.yaml
- conf/rest/default.yaml
4 metrics are exported from this template,
> feat: adding storage-units rest call in asar2

- cmd/tools/grafana/dashboard_test.go
- grafana/dashboards/cmode/snapmirror_destinations.json
> feat: adding total throughput panel of destination volume of sm-sv

- third_party/shirou/gopsutil/v4/internal/common/common.go
- third_party/shirou/gopsutil/v4/internal/common/warnings.go
See https://github.com/shirou/gopsutil/releases/tag/v4.25.9
> chore: track upstream gopsutil changes

- docs/prepare-cdot-clusters.md
Thanks, @xK3v for raising this issue
> doc: Use consistent role name in documentation
