NetApp/harvest

SUPPORT.md

- documentation link was broken
- added link to architecture and contributing docs
- updated slack link (was pointing to the old slack channel)

update slack link, fix broken documentation link

---

cmd/poller/options/options_test.go

This test is in response to issue #28.
Reverted the [fix](https://github.com/NetApp/harvest/commit/abd1517e347f091d535ae71decfe8b84b211e0c1) and verified the test fails with the following output.
```
--- FAIL: TestConfigPath (0.00s)
options_test.go:13: options.Config expected=["foo"], actual was=["harvest.yml"]
```
Apply the fix and test passes.

Add test to ensure config path is not overwritten

---

SUPPORT.md

I replaced the link with the short link.. www.netapp.io/slack the other link either is broken or will be in a week or two.. so use the short one.  I added this as a comment in the other issue/PR I guess you missed it.

fixing slack signup link

---

cmd/collectors/zapiperf/zapiperf.go

fix issue mentioned in #40 
the ZapiPerf collector should rename the string counter `instance_name` to match its object name (e.g. `volume`). There is a bug that requires currently to do the renaming in the template, otherwise the label will be missing in the output metrics.

fix issue that instance_name not renamed/exported

---

cmd/tools/doctor/doctor_test.go
cmd/tools/doctor/testConfig.yml
pkg/conf/conf.go

This change only addresses passwords in Pollers and Defaults. The bigger refactor is to use HarvestConfig through out the codebase, but that was too big a change at the moment. That change touches a lot more code.
When that change is made, the code in conf.LoadConfig can be removed.

Handle special characters in passwords

---

cmd/tools/grafana/grafana.go
cmd/tools/grafana/grafana_test.go

`harvest/grafana` should not rewrite https connections into http
Fixes #111

Allow insecure Grafana TLS connections

---

pkg/errors/errors.go

Example below.
{"level":"error","Poller":"F2240-127-26","collector":"ZapiPerf:Volume","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"403","source":"client.go"},{"func":"(*Client).InvokeWithTimers","line":"317","source":"client.go"},{"func":"(*ZapiPerf).PollData","line":"206","source":"zapiperf.go"},{"func":"(*task).Run","line":"60","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"269","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}],"error":"api request rejected => Incorrect counter list: \"timestamp\", non-existent counters are not allowed.","caller":"/home/rahulg2/code/github/harvest/cmd/poller/collector/collector.go:303","time":"2021-06-06T08:55:07-04:00"}

enable stacktrace during errors

---

cmd/harvest/harvest.go

Two cases are improved here:
1) Harvest detects when there is a stale pidfile and correctly restarts the poller process. A stale pidfile is when the pidfile exists in `/var/run/harvest` but there is no running process associated with that pid.
1) Harvest no longer suggests killing an already running poller when you try to start it. This is a a no-op.
Fixes #123

Improve harvest start behavior

---

Makefile

Add -trimpath to go build so errors and stacktraces print
with module path@version instead of this
{"level":"info","Poller":"infinity","collector":"ZapiPerf:WAFLAggr","caller":"/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/collector/collector.go:318","time":"2021-06-11T13:40:03-04:00","message":"recovered from standby mode, back to normal schedule"}

Trim absolute file system paths

---

cmd/collectors/unix/main.go

When a poller in harvest.yml is changed while a unix collector is running it panics
Fixes #160

Fix panic in unix.go

---

conf/zapi/cdot/9.8.0/disk.yaml

that disk status is correctly reported
Fixes #182

Store reason as a label for disk.yaml so

---

cmd/harvest/harvest.go

for status checks
Makes a big difference on Mac when process is not found
Goes from 19.5 seconds to (not) start 27 pollers to
1.9 seconds

Reduce the amount of time and attempts spinning

---

grafana/prometheus/harvest_dashboard_shelf.json

Adding override option to show values as JSON values.
So that it will show 1.10, 1.20 to 1.1, 1.2 which is the actual values.

shelf dashboard: adding override option for shelf field

---

grafana/prometheus/harvest_dashboard_node.json

changed Throughput unit to Bps and Iops unit to iops.
Testing grafana UI: http://10.249.31.109:3000/d/P_2gObR7z/netapp-detail-node?orgId=1
Issues mentioned in bug:
1. Cluster variable not based on datacenter variable
2. Typo Thoughput (2x)
3. Units of Throughput panel set to seconds (4x)
4. Unit of IOPS panel set to seconds (5x)
Resolved 2, 3 and 4.
But pending for 1 as after changing from cluster variable to datacenter, it's failing for all queries. Working on that issue now.

Node Dashboard Bugs

---

grafana/prometheus/harvest_dashboard_cluster.json

There are few custom changes in my local grafana, due to which it shows as wrong units, but later when deleted all existing dashboards and imported again, apart form this graph, all 7 dashboards are fine. This was the last one.

IOPS in B/s unit

---

grafana/prometheus/harvest_dashboard_volume.json

supporting filter based on the chosen volume in volume dashboard.
Graphs:
These are the current numbers/graphs which supports volume filter:
- Average latency [number]
- Throughput [number]
- Total iops [number]
- Average latency [graph]
- Total average throughput [graph]
- Total iops [graph]
- volumes in cluster [table]
These are cluster scope graphs and not supporting filter on svm and volume: NO CHANGE HERE
- read latency
- read throughput
- read iops
- write latency
- write throughput
- write iops
Also, there is typo in write throughput graph [changed form read to write].
Grafana: http://10.249.24.71:3000/d/mRFX09Rnk/netapp-detail-volume?orgId=1&refresh=1m&var-Datacenter=DC-03&var-Cluster=F8080-32-25&var-SVM=All&var-Volume=MDV_CRS_d33421f0984011eb814a00a0986abd71_B&var-TopResources=5

Volume dashboard select option

---

cmd/poller/poller.go
pkg/conf/conf.go
pkg/tree/node/node.go

struct instead of nodes
The methods suffixed with 2: `GetPollers2`, `GetPoller2`, etc. will replace the node based versions once we update all senders
Compare the two approaches to union in Poller.Union2 and Conf.Union

WIP Poller should use Harvest config

---

cmd/harvest/harvest.go
pkg/util/util.go

Injecting into a poller's environment to disambiguate the process doesn't work on Mac and on Unixes, non-root users can not read /proc

refactor: remove dead HarvestTag code

---

conf/zapiperf/cdot/9.8.0/qtree.yaml
conf/zapiperf/default.yaml

Thanks to Martin Möbius on Slack for contributing
```
curl -s 'http://127.0.0.1:13000/metrics' | rg "^qtree" | head
qtree_internal_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtree="",volume="san_vs_4_vl_34",svm="san_vs_4"} 0
qtree_nfs_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtree="",volume="san_vs_4_vl_34",svm="san_vs_4"} 0
qtree_total_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtree="",volume="san_vs_4_vl_34",svm="san_vs_4"} 0
qtree_cifs_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtree="",volume="san_vs_4_vl_34",svm="san_vs_4"} 0
qtree_cifs_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtree="san_vs_3_vl_19_qtree_1",volume="san_vs_3_vl_19",svm="san_vs_3"} 0
qtree_internal_ops{cluster="stiA400-7591614006449",datacenter="nane1",qtr …
```

feat: collect qtree ops

---

cmd/tools/zapi/zapi.go

```
bin/zapi --config harvest.ved.yml --poller venkat show data --object qtree --counter nfs_ops
[instance-data]                   -                                   *
[aggregation]                   -                                   *
[aggregation-data]            -                                   *
[constituent-count]         -                                   1
[result]                    -                complete_aggregation
[counters]                      -                                   *
[counter-data]                -                                   *
[name]                      -                             nfs_ops
[value]                     -                                   0
[name]                          - san_vs_4:san_vs_4_vl_9/san_vs_4_vl_9_qtree_2
[sort-id] …
```

fix: zapi tool should limit perf-o-g-i to subset of counters

---

cmd/poller/poller.go

The cert and key values specified in harvest.yml were ignored because of an incorrect nil check.
With this fix, a relative or absolute path can be specified for
```
ssl_cert: path/to/cbg-inf.pem # absolute
ssl_key: cbg-inf.key          # relative to Harvest home
```

fix: certificate auth should honor path in harvest.yml

---

cmd/harvest/harvest.go
cmd/tools/rest/rest.go
cmd/tools/rest/swag.go
cmd/tools/zapi/zapi.go

Added
```
-c, --cross string         Cross-field queries return rows where any field in a specified set of fields matches the query
--field string         Query a field by value. If the value contains query characters (*|,!<>..), it must be quoted to avoid their special meaning
*         wildcard
< > <= >= comparisons
3..10     range
!water    negation
3|5       matching value in a list
{} and "" escape special characters
```

feat: add richer set of REST queries

---

Makefile
cmd/harvest/harvest.go
cmd/harvest/version/version.go
cmd/harvest/version/version_test.go

Fixes #323 
We usually tag the release branch with the release tag instead of the main branch. That caused our Makefile to embed the wrong RELEASE string when building locally. Jenkins works fine because we explicitly pass the RELEASE string. 
I changed the Makefile to pick the latest tagged commit across all branches instead of the latest tag on the current branch. That way local builds include the most recent tag too.
Local Build with version check (the release is `v21.05.3` instead of `v21.05.0`)
```
make build
bin/harvest version
harvest version 21.07.2020-v21.05.3 (commit 5836229) (build date 2021-07-20T20:26:39-0400) darwin/amd64
checking GitHub for latest... you have the latest ✓
```
Build a version of Harvest from the past
```
RELEASE=17.05.1 make build
bin/harvest version
harvest …
```

feat: harvest version checks for latest release

---

cmd/tools/grafana/grafana.go
cmd/tools/grafana/grafana_test.go
grafana/prometheus/harvest_dashboard_metadata.json

fixes #332
For the first query, I couldn't find a better solution than just change the query in the dashboard. (Trying to match this with another regex, seems likely to produce false positives).
For the second query, a more precise regexp is used. Tests are updated as well.

fix: false negatives by prefix matcher

---

grafana/prometheus/harvest_dashboard_svm.json

Dashboard for SVM, for now with drilldown for NFSv3 only.

feat: SVM dashboard with NFSv3 Frontend Drilldown

---

cmd/tools/zapi/show.go
cmd/tools/zapi/zapi.go

Original printing is still supported with new flag (`--write color`). Default flag is `xml`.
This change makes post-processing zapi responses much easier - for example to convert xml to json
```
bin/zapi --poller infinity show data --api storage-disk-get-iter | dasel -r xml -w json
...
"disk-stats-info": {
"average-latency": "0",
"bytes-per-sector": "520",
"disk-io-kbps": "197",
"disk-iops": "6",
"disk-uid": "5002538B:08448840:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000",
"path-error-count": "0",
"power-on-time-interval": "86994000",
"sectors-read": "8448345263",
"sectors-written": "638497917"
},
"disk-uid": "5002538B:08448840:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000"
}
]
},
"num-records": "24"
}
```

feat: zapi tool should print xml

---

grafana/dashboards/harvest_dashboard_disk.json

type and status are fetched from disk_labels metric.
status is actual outage field, if it's empty which is OK state, else gives reason. One issue found that sometimes outage info don't come in response. I need to figure it out.
disk_labels{aggr="aggr0_F8080_32_25_01", cluster="F8080-32-25", datacenter="DC-03", disk="1.0.12", failed="false", instance="localhost:12991", job="prometheus1", model="X446_1625200MCSG", node="F8080-32-25-01", owner_node="F8080-32-25-01", serial_number="S142NEAG200663", shared="true", shelf="0", shelf_bay="12", type="SSD"}
disk_labels{cluster="F8080-32-25", datacenter="DC-03", disk="1.10.2", failed="false", instance="localhost:12991", job="prometheus1", model="X446_1625200MCSG", node="F8080-32-22-01", outage="unknown", owner_node="F8080-32-22-01", …

feat: adding type and status in disk dashboard

---

cmd/harvest/harvest.go
pkg/conf/conf.go

Second PR to fix issue #357
Changed to things:
* refactored `cmd/harvest/harvest.go` to use the struct-based poller configs (this solves Poller parameters not being merged with Defaults)
* in `conf.loadPrometheusExporterPortRangeMapping()` use `localhost` when checking for free ports
(Re-opened PR since the commit messages were failing the commitlint-check)

fix: Prometheus port_range-related issue 357 (Re-opened PR)

---

grafana/dashboards/harvest_dashboard_disk.json

Result of the query: label_join(disk_labels{datacenter="DC-03",cluster="F8080-32-25"}, "diskStatus", " ","NonSupportedField", "outage")
1. When no outage info available in disk_labels:
disk_labels{aggr="aggr0_F8080_32_25_01", cluster="F8080-32-25", datacenter="DC-03", disk="1.0.12", diskStatus=" ", failed="false", instance="localhost:12991", job="prometheus1", model="X446_1625200MCSG", node="F8080-32-25-01", owner_node="F8080-32-25-01", serial_number="S142NEAG200663", shared="true", shelf="0", shelf_bay="12", type="SSD"} | 1
-- | --
2. When outage info available in disk_labels:
disk_labels{cluster="F8080-32-25", datacenter="DC-03", disk="1.10.4", diskStatus=" unknown", failed="false", instance="localhost:12991", job="prometheus1", model="X446_1625200MCSG", node="F8080-32-22-01", outage="un …

fix: supporting diskstatus(outage info) for all cases in disk dashboard

---

cmd/exporters/prometheus/README.md
cmd/tools/doctor/testdata/testConfig.yml
harvest.cue
harvest.yml

Prometheus `addr` is deprecated. Use [local_http_addr](https://github.com/NetApp/harvest/tree/main/cmd/exporters/prometheus#parameters) instead or omit entirely if you want to use `0.0.0.0`.

docs: remove references to deprecated addr

---

cmd/harvest/harvest.go
cmd/tools/grafana/grafana.go
cmd/tools/grafana/main/main.go
pkg/conf/conf.go

directory.
Fixes #368
This change addresses the problem when using `bin/poller` but does not work with `bin/harvest`.
The issue with `bin/harvest` is the `os.Exec`-ed executables are not found without more directory work.
The workaround is `cd` into the installation directory before executing `bin/harvest`

fix: HARVEST_CONF should be consulted when loading files from conf

---

README.md
cmd/collectors/zapi/collector/zapi.go
harvest.cue
pkg/api/ontapi/zapi/client.go
pkg/conf/conf.go

when a `poller` includes a `log` section, the matching collector will log that collector's zapi request/response
e.g.
```
Pollers:
infinity:
datacenter: ctl
addr: 10.10.10.10
log:
- Zapi                <==== the Zapi collector should log each ZAPI's request/response
- ZapiPerf         <==== the ZapiPerf collector should do the same
```

feat: log zapi request/response

---

cmd/tools/doctor/doctor.go
cmd/tools/doctor/testdata/testConfig.yml

Re-add when PrometheusConsul is implemented. Until then, it's confusing to include as an example

refactor: remove PrometheusConsul from test

---

rpm/spec

fix: rpmbuild should ignore python errors

---

cmd/collectors/zapi/README.md
cmd/collectors/zapi/collector/parsers.go

Re-opened PR #388, addressed comments.

refactor: Zapi collector should use parameter to override default metric type

---

cmd/collectors/zapi/README.md
cmd/collectors/zapiperf/README.md

tried to improve documentation of our two main collectors:
* the sensors example belonged to zapi: moved it from the zapiperf doc to the zapi doc
* added example of creating subtemplate for the zapiperf collector
* clarified a little bit how to change existing subtemplates
* re-ordered a few sections for more clarity

docs: subtemplate examples for zapi and zapiperf collectors

---

grafana/dashboards/harvest_dashboard_disk.json

local testing grafana: http://10.249.28.157:3000/.  [used grafana version for testing: 7.5.10]
Covered these:
1. status column issue
2. disk utilization percentage
I don't think we have issue with 'Disk and Take Drives Throughput' as metric values are in µs and it should be.

fix: disk dashboard status column

---

cmd/poller/poller.go

Instead of logging error when custom.yaml is missing like this
```
1:47PM WRN command-line-arguments/poller.go:523 > Unable to load template. error="open conf/zapi/custom.yaml: no such file or directory" Poller=venkat
```
log was warning like this
```
1:50PM WRN command-line-arguments/poller.go:523 > Unable to load template. Poller=venkat err="open conf/zapi/custom.yaml: no such file or directory"
```
The first is in red while the second is a normal log msg

fix: don't log err when file is missing

---

cmd/poller/collector/collector.go
pkg/matrix/matrix.go

fix makes sure that metadata of each task is reset only when it's being executed.
other minor changes:
- remove dead metadata metrics: `content_length` and `api_time_percent`
- set the `poll_time` and `task_time` metrics for all tasks, not just `data`

fix: reset metadata for each task

---

grafana/dashboards/harvest_dashboard_network.json

FCP send and receive should show like Ethernet send and receive. currently, fcp_write_data and fcp_read_data metric value is 0, that's why graph is horizontal line with 0 B/s.

fix: FCP send, receive charts with units

---

cmd/poller/poller.go
cmd/poller/schedule/schedule.go

If the schedule is once a week, the first time autosupport runs, it instead runs after two weeks.
```
time |---X----f----y----|
^    ^               
|    |                 
now --     ---- future                 
```
That's because when a task is created and added to the schedule at X, a time in the future is calculated (current time + 1 week), at f.
Later, when a go routine checks if the future task is due to run, it determines that by calculating: one week - time.Since(f), but since f is already a week in the future. The task won't run until y, which is two weeks after X was scheduled.
The fix: when the task is scheduled, schedule it at the current time instead of current time + 1 week.

fix: first autosupport runs after delay

---

conf/zapiperf/cdot/9.8.0/nfsv4.yaml

Thanks to Jeff Asher for reporting this

fix: typo in nfsv4 template causes mislabeling

---

conf/zapi/7mode/8.6.0/node.yaml
grafana/dashboards/7mode/harvest_dashboard_aggregate7.json
grafana/dashboards/7mode/harvest_dashboard_cluster7.json
grafana/dashboards/7mode/harvest_dashboard_network7.json
grafana/dashboards/7mode/harvest_dashboard_nvme_fc7.json
grafana/dashboards/harvest_dashboard_aggregate.json

Added global label only in 7mode node.yaml, we would use the node_labels{system_type} to take decision of cmode/7mode.
Identified gaps:
- 7 mode don't have product-version in system-get-info zapi
- 7 mode don't have tx_hw_errors, rx_alignment_errors, rx_crc_errors, rx_length_errors in nic_common object
Changes done:
Cluster
- node_new_status to cluster_new_status
Aggregate
- Physical Space Used to space used 
- removed Capacity Tier Used(aggr_space_capacity_tier_used), Data Compaction space used(aggr_space_data_compaction_saved), Space Reserved for Snapshot %(space reserved for snapshot) panels which are nor available in 7 mode zapi response. 
Network
- Removed Transmission interrupts, Transmission errors, Link Down, Link Failure panels 
Network with Nvme/FC
- Removed Nvme/FC receive, …

feat: split dashboards for 7mode - part1

---

README.md
cmd/exporters/influxdb/README.md
cmd/exporters/influxdb/influxdb.go
conf/zapiperf/cdot/9.8.0/system_node.yaml
grafana/dashboards/influxdb/harvest_dashboard_aggregate.json
grafana/dashboards/influxdb/harvest_dashboard_cluster.json
grafana/dashboards/influxdb/harvest_dashboard_headroom.json
grafana/dashboards/influxdb/harvest_dashboard_metadata.json
grafana/dashboards/influxdb/harvest_dashboard_network.json
grafana/dashboards/influxdb/harvest_dashboard_shelf.json
grafana/dashboards/influxdb/harvest_dashboard_snapmirror.json
grafana/dashboards/influxdb/harvest_dashboard_svm.json

This PR provides dashboards for the InfluxDB by me and @SamyukthaM. It also fixes #430.
* At the current state, the dashboards can not be imported with the grafana-tool. This will be fixed with a different PR.
* PR includes 8 dashboards, they are far from complete or perfect, but it's a start
* most are based on our Prometheus-dashboards, but also introduce several improvements
* they are tested only against cdot systems, they should work for 7modes to the same extend as our Prometheus-based dashboards, but since we are likely to split them up, I did not spend time here
* A few things were necessary to fix:
* the InfluxDB exporter will check for conflicting metric names and rename them
* duplicate metrics interfere with some dashboards, that's why I removed `update` from …

feat: Influxdb dashboards

---

conf/zapi/7mode/8.6.0/status_7.yaml
conf/zapi/default.yaml
grafana/dashboards/7mode/harvest_dashboard_cluster7.json

using diagnosis-config-get-iter zapi to get node status with monitor type as node-connect

fix: consuming node status from diagnosis-config-get-iter zapi for 7mode

---

cmd/tools/grafana/grafana.go
conf/zapi/7mode/8.6.0/lun.yaml
conf/zapi/7mode/8.6.0/volume.yaml
conf/zapiperf/7mode/8.2.5/lun.yaml
conf/zapiperf/7mode/8.2.5/volume.yaml
grafana/dashboards/7mode/harvest_dashboard_lun7.json
grafana/dashboards/7mode/harvest_dashboard_metadata7.json
grafana/dashboards/7mode/harvest_dashboard_network7.json
grafana/dashboards/7mode/harvest_dashboard_node7.json
grafana/dashboards/7mode/harvest_dashboard_nvme_fc7.json
grafana/dashboards/7mode/harvest_dashboard_volume7.json
grafana/dashboards/harvest_dashboard_network_detail.json
grafana/dashboards/harvest_dashboard_node_details.json
grafana/dashboards/harvest_dashboard_volume_details.json

For 7mode system, vol create is based on aggr name, means aggr+vol name is unique. 
```
tobago-2> vol help create 
vol create <vol-name>
{ [-l <language-code>] [-s {none | file | volume}]
<hosting-aggr-name> <size>[k|m|g|t] }
|
{ [-l <language-code>] <hosting-aggr-name>
[size[k|m|g|t]] -S <remotehost:remotevolume> }
|
{ [-f] [-l <language-code>] [-m] [-n] 
[-L [compliance | enterprise]]
[-r <raid-group-size>] [-t {raid4 | raid_dp}]
<disk-list> }
-- create a new volume, either a flexible volume from an existing
aggregate, or a traditional volume from a disk list.  A disk
list is either
<ndisks>[@<disk-size>] 
or
-d <disk-name1> <disk-name2> ... <disk-nameN>
[-d <disk-name1> <disk-name2> ... <disk-nameN>].
```
link: https://library.netapp.com/ecm/ecm_download_file/ECMP1196890
Few examples …

feat: split dashboards for 7mode - volume

---

cmd/exporters/influxdb/influxdb.go
cmd/exporters/influxdb/influxdb_test.go
cmd/tools/doctor/testdata/testConfig.yml
jenkins/artifacts/jenkinsfile
pkg/util/util.go

Add url encoding for bucket and org parameter in InfluxDB parameters

fix: escape whitespace in InfluxDB exporter

---

conf/zapi/7mode/8.6.0/node.yaml
conf/zapi/7mode/8.6.0/status_7.yaml
grafana/dashboards/7mode/harvest_dashboard_cluster7.json

Before the change:
and we only want node-connect monitor for our use-case in 7mode
After the change:
removed the node_7mode_status metric and updated the dashboards as well.

fix: node_new_status correction for 7mode

---

cmd/tools/zapi/get_attrs.go
cmd/tools/zapi/zapi.go
pkg/tree/node/node.go

```
bin/zapi -p u2 show attrs --api storage-disk-get-iter
```
shows this
```
[storage-sed-info]                -
[data-key-id]                   -                              string
[fips-key-id]                   -                              string
[is-fips-sed]                   -                             boolean
[is-non-fips-sed]               -                             boolean
[is-power-on-lock-enabled]      -                             boolean
[is-sed]                        -                             boolean
[protection-mode]               -                              string
[storage-ssd-info]                -
[percent-rated-life-used]       -                             integer
[percent-spares-consumed]       -                             integer …
```

feat: print counter type when querying zapi

---

jenkins/artifacts/jenkinsfile

1. No need to add trigger directive for branch jobs

ci: remove trigger from jenkins file

---

cmd/collectors/zapiperf/plugins/nic/nic.go
grafana/dashboards/7mode/harvest_dashboard_network7.json
grafana/dashboards/cmode/harvest_dashboard_network_detail.json

Issues: [with fix]
- all Variables have sorting disabled
--> All variables(cluster, node, Eth, Fcp) would support sorting now but Datacenter
- Ethernet Receive & Ethernet Send have Value Mappings defined that makes the timeseries show "UP" when there is 0 traffic
--> Removed the value mapping as it's not required here, When there is 0 traffic, it would show 0 B/s
- Port Utilization uses wrong unit, Percent 0-100 instead 0-1
--> Corrected the percent issue 
- Top Resources variable is not used
--> It's used for 8 graphs, Ethernet drilldown: send throughput, receive throughput, FC drildown:  send throughput, receive throughput, send latency, receive latency, link down, link failure
--> There is identified issue for TopN resource https://github.com/NetApp/harvest/issues/587, we are working …

fix: network detail dashboard issues

---

cmd/tools/grafana/grafana.go

Happens when using env var `HARVEST_CONFIG`

fix: grafana import saves token to wrong file

---

grafana/dashboards/cmode/harvest_dashboard_mcc_cluster.json

Fixes : #685 
Details :
1. Enable sorting for all variables
2. Change threshold limit for "Volume Average Latency" and "FCVI Write Latency"
3.  Update "MetroCluster Disk Drilldown" Panels User Reads & User Writes  to use IOPS unit
4. Microseconds for "MetroCluster Disk Drilldown" Latency Panels and  "MetroCluster FCVI Drilldown" Panel "FCVI Latency" 
5. MB/s for "Disk and Tape Adapter Drilldown" Panel "Adapter Read Data" and "MetroCluster FibreBridge/Array Drilldown" Panel "FibreBridge/Array WWPN - Read Data"

feat: fix unit changes and threshold settings for mcc

---

cmd/collectors/zapiperf/plugins/volume/volume.go

**Fix**: replace the flexgroup instance key from {node}.{svm}.{volume} to {svm}.{volume}
**Before the changes:** [enabled debug log to see more detail] earlier we treated as 4 flexgroup when spanned across nodes
```
hardikl@hardikl-mac-0 harvest % ./bin/poller --poller cluster-06 --loglevel 2  --promPort 12991  -c ZapiPerf --config harvest.yml
6:14PM INF ./poller.go:178 > log level used: info Poller=cluster-06
6:14PM INF ./poller.go:179 > options config: harvest.yml Poller=cluster-06
6:14PM INF ./poller.go:216 > started in foreground [pid=18512] Poller=cluster-06
6:14PM INF goharvest2/cmd/poller/collector/helpers.go:122 > best-fit template [conf/zapiperf/cdot/9.8.0/volume.yaml] for [9.10.1] Poller=cluster-06 collector=ZapiPerf:Volume
6:14PM INF ./poller.go:340 > Autosupport scheduled. …
```

fix: consolidate all flexgroup_constituents across nodes

---

cmd/collectors/zapi/plugins/quota/quota.go
conf/zapi/7mode/8.6.0/qtree.yaml

7mode testing:
1. volume uniqueness: same name volume can't be created in cluster. volume is unique within cluster irrespective of vfiler.
a. created volab in aggr tobago_2_aggr0
```
tobago-2> vol create volab tobago_2_aggr0  20m 
Creation of volume 'volab' with size 20m on containing aggregate
'tobago_2_aggr0' has completed.
tobago-2> vol status                          
Volume State           Status                Options
vol_4kb_neuM online          raid_dp, flex         snapmirrored=on, create_ucode=on, 
snapmirrored          convert_ucode=on, fs_size_fixed=on
read-only             
64-bit                
vol0 online          raid4, flex           root, create_ucode=on, convert_ucode=on
64-bit                
D online          raid4, flex           snapmirrored=on, create_ucode=on, …
```

fix: handling vfiler for qtree 7mode

---

cmd/collectors/zapi/plugins/quota/quota.go

**Issue:** qtree instance key order is different in cmode and 7mode.
**Reason:** qtree instance key formation is based on the order of fields in the response. In cmode, it's order as qtree,volume and svm, but in 7mode, it's volume, qree.
Cmode qtree key
```
3:41PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:271 > keys=[qtree1 test123 test] keypaths=[[qtree-info volume] [qtree-info vserver] [qtree-info qtree]] found=true Poller=cluster-07 collector=Zapi:Qtree
3:41PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:280 > added instance [qtree1.test123.test] Poller=cluster-07 collector=Zapi:Qtree
```
7mode qtree key:
```
3:44PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:271 > keys=[vol0 qt1] keypaths=[[qtree-info volume] [qtree-info qtree]] found=true Poller=cluster-05 …
```

fix: quota plugin qtreekey issue

---

cmd/harvest/harvest.go
cmd/poller/options/options.go
cmd/poller/poller.go

Fixes #810
Add `logtofile` option to `bin/harvest` and `bin/poller`. When running in the foreground, use file logging, instead of stdout

feat: Harvest should support logging to file when running in foreground

---

cmd/collectors/rest/plugins/volume/volume.go
cmd/collectors/rest/rest.go
cmd/collectors/rest/templating.go
cmd/poller/poller.go
cmd/tools/rest/client.go
conf/rest/9.12.0/status.yaml

```json
{
"Target": {
"Version": "9.11.0",
"Model": "cdot",
"Serial": "redacted",
"Ping": 0,
"ClusterUuid": "redacted"
},
"Harvest": {
"HostHash": "redacted",
"UUID": "redacted",
"Version": "22.02.0915",
"Release": "v21.11.1",
"Commit": "7c4e4c0",
"BuildDate": "2022-02-09T15:04:03+0530",
"NumClusters": 1
},
"Platform": {
"OS": "darwin",
"Arch": "darwin",
"Memory": {
"TotalKb": 16777216,
"AvailableKb": 5931728,
"UsedKb": 10845488
},
"CPUs": 1
},
"Nodes": {
"Count": 2,
"DataPoints": 26,
"PollTime": 2324723,
"ApiTime": 2009857,
"ParseTime": 314359,
"PluginTime": 11,
"Ids": [
{
"serial-number": "4083664-19-5",
"system-id": "4083664195"
},
{
"serial-number": "4083664-19-6",
"system-id": "4083664196"
}
]
},
"Volumes": {
"Count": 4,
"DataPoints": 116,
"PollTime": 3581761,
"ApiTime": 2017120, …
```

feat: asup rest

---

cmd/collectors/zapi/plugins/quota/quota.go

Added one logger to verify only tree quotas would be fetched. First call fetched 20 quotas [16 tree and 4 user quotas]
Before the changes:
```
hardikl@hardikl-mac-0 harvest % ./bin/poller --poller cluster-01  --promPort 12988 --config harvest.yml
4:31PM INF ./poller.go:182 > log level used: info Poller=cluster-01
4:31PM INF ./poller.go:183 > options config: harvest.yml Poller=cluster-01
4:31PM INF ./poller.go:220 > started in foreground [pid=11910] Poller=cluster-01
4:31PM INF goharvest2/cmd/poller/collector/helpers.go:123 > best-fit template [conf/zapi/cdot/9.8.0/qtree.yaml] for [9.3.0] Poller=cluster-01 collector=Zapi:Qtree
4:31PM INF ./poller.go:344 > Autosupport scheduled. Poller=cluster-01 asupSchedule=24h
4:31PM INF ./poller.go:353 > poller start-up complete Poller=cluster-01
4:31PM …
```

fix: fetching only tree quotas in zapi request

---

cmd/collectors/rest/plugins/svm/svm.go
cmd/collectors/rest/rest.go
conf/rest/9.12.0/security_audit_dest.yaml
conf/rest/9.12.0/security_ssh.yaml
conf/rest/9.12.0/svm.yaml
conf/rest/default.yaml
grafana/dashboards/cmode/harvest_dashboard_compliance.json
grafana/dashboards/cmode/harvest_dashboard_security.json
integration/test/dashboard_test.go

UI Feedback:
> security dash: split--> compliance and security
> color/image in table  : done
> --> image via plugin(https://grafana.com/grafana/plugins/dalvany-image-panel/?tab=installation), 
> https://grafana.com/docs/grafana/latest/visualizations/table/
> --> background color
> description: done
`expiry panel should have cluster name: in-progress
`
1. Compliance 
2. Security

feat: split into 2 - compliance and security

---

grafana/dashboards/cmode/harvest_dashboard_volume_details.json

Convert Grafana graphs to time-series panels
Related to #967

fix: volume dashboard should collapse `Per Volume Statistics`

---

conf/zapi/cdot/9.8.0/aggr.yaml

1. aggrs before any changes
aggr_labels for rest
aggr labels for zapi (root_aggr label is visible, as we only show non-root aggr, so removed that label)
aggr metrics for both
2. Added the below changes to add label and exclude from label and metrics
aggr labels for zapi
aggr metrics for both

fix: exclude root aggr

---

conf/rest/9.12.0/volume.yaml
conf/restperf/9.12.0/volume.yaml
conf/zapi/7mode/8.6.0/volume.yaml
conf/zapi/cdot/9.8.0/volume.yaml
conf/zapiperf/7mode/8.2.5/volume.yaml
conf/zapiperf/cdot/9.8.0/volume.yaml

Below details from the Netapp_Harvest_IAG_1.X.pdf
****C.** Use a blacklist to prevent visibility of temporary volumes [optional]**
Harvest will discover all instances of objects such as lifs, volumes, and luns on the cluster. Some of these instances may be temporary, such as those used by backup jobs, and add undesired clutter and storage consumption. Graphite provides the ability to blacklist (block) incoming metrics that match a regular expression string and this feature can be used to block metrics for these temporary instances.
The following steps can be used to block metrics on temporary volumes that are often created by NetApp and NetApp partner software integrations:
1. Login the graphite host and if not logged in as the root superuser, become root using sudo:
```
[user@host ~]# …
```

fix: ignore transient volumes

---

cmd/collectors/zapi/plugins/volume/volume.go
grafana/dashboards/cmode/harvest_dashboard_data_protection.json

Found some minor issues in dashboard.
1. not able to stop the batchzapi call even when all records were fetched. 
reason: In case of tag=initial, it will invoke batch call and when it finished, we got tag="". As we have same util function for batch and non-batch zapi call, In this case, it is invoking next non-batch call and duplicate instance key error is found in volume plugin 
2. grafana panel error in data protection dashboard

fix: some minor issues in dashboard

---

cmd/collectors/zapiperf/plugins/volume/volume.go
conf/zapiperf/cdot/9.8.0/volume.yaml

Thanks to Papadopoulos Anastasios for raising on Slack.
The label `type` was changed to `style` for perf zapi volume.
Before:
```
volume_read_latency{aggr="umeng_aff300_aggr1",cluster="umeng-aff300-05-06",datacenter="dc-1",node="umeng-aff300-06",type="flexgroup",svm="vs_test",volume="vol_fc_1"} 100.5
```
After
```
volume_read_latency{aggr="umeng_aff300_aggr1",cluster="umeng-aff300-05-06",datacenter="dc-1",node="umeng-aff300-06",style="flexgroup",svm="vs_test",volume="vol_fc_1"} 100.5
```

feat: make perf zapi volume labels consistent with zapi volume

---

conf/zapi/cdot/9.8.0/security_certificate.yaml

We were using different `-cert-name` for all svms(admin svm as well) for local clusters, so haven't identify this issue earlier. 
I have reproduce this issue locally by creating the same `-cert-name` 
```
ocum-infinity::> security certificate create -cert-name 0016d08e-807d-4159-a6fe-feec7e344cc0 -vserver dp_test -common-name anvtest -type server 
ocum-infinity::> security certificate show -cert-name 0016d08e-807d-4159-a6fe-feec7e344cc0
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
dp_test    16F6A6EC8DE4E0A3 
0016d08e-807d-4159-a6fe-feec7e344cc0   server
Certificate Authority: anvtest
Expiration Date: Thu Jun 08 09:04:08 2023
ocum-infinity 
2908E23B …
```

fix: security certificate duplicate key issue

---

conf/zapi/cdot/9.8.0/security_account.yaml
pkg/tree/node/node.go

In most of the clusters, this field `remote-switch-ipaddress` won't be available as it's based on the remote switch. That's why we haven't encountered in our UTs.
**Fix:** added the `remote-switch-ipaddress` as instanceKey
**Detail:** 
- we have restriction in ZAPI workflow that if any key is not exist in response then we ignore/skip that instance
- This logic has been changed, and it will only skip the instance when all the asked keys were not exist in response.
- If one key exist, we would go ahead and parse that instance.

fix: duplicate instance key for SecurityAccount

---

cmd/collectors/rest/plugins/volume/volume.go
cmd/collectors/restperf/plugins/volume/volume.go
cmd/collectors/zapiperf/plugins/volume/volume.go
conf/rest/9.12.0/svm.yaml
conf/rest/9.12.0/volume.yaml
conf/zapi/cdot/9.8.0/svm.yaml
conf/zapi/cdot/9.8.0/volume.yaml

Fix details:
Rest/Zapi: aggr, node labels in Rest should be same as Zapi. 
- node from private cli
- aggr from private cli
- aggrUuid - other use case in plugin for isHardwareEncrypted label, handled in plugin
RestPerf/ZapiPerf
- removed aggr, node labels in perf plugin for flexgroup.
Svm:
- Zapi can have aggr-list(list not supported) or root-volume-aggr, both would not be much useful at svm level
- Rest can have aggr-list or root-volume-aggr, both would not be much useful at svm level, - should be parity with Zapi
- we don't use aggr field from svm

fix: remove aggr, node in rest for flexgroup

---

conf/zapi/cdot/9.8.0/security_certificate.yaml

Adding serial-number to key because
- it's already exist as label in template, so no new addition in template.
- comman-name would be small or similar to cert-name as it's used to form cert-name.  cert-name=comman-name+serial 
cluster 10.193.6.61:
other cluster > 9.1:

fix: add serial number as key for certificate

---

grafana/dashboards/cmode/harvest_dashboard_compliance.json

This column #H is not used anywhere in the table.
Rest of the places `security_audit_destination_status` metric used as `security_audit_destination_status{datacenter="$Datacenter",cluster=~"$Cluster", protocol!="tcp_encrypted"}`.

fix: remove unused metric

---

grafana/dashboards/7mode/harvest_dashboard_volume7.json
grafana/dashboards/cmode/harvest_dashboard_data_protection_snapshot.json
grafana/dashboards/cmode/harvest_dashboard_snapmirror.json
grafana/dashboards/cmode/harvest_dashboard_volume_details.json

When color is single(fixed) then displaymode should be auto to visible in light UI
When color is based on threshold then displaymode as color-background-solid would be visible in light UI.

fix: color changes for data protection + few other dashboards

---

cmd/collectors/rest/plugins/certificate/certificate.go

Identify by Rahul on cluster 10.236.42.3, 
security_certificate_labels [svm] is missing svm in rest vs zapi.
Without the change:
With this change:

fix: label parity with zapi-rest

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/collectors/unix/process.go
cmd/exporters/influxdb/influxdb.go
cmd/harvest/version/version.go
cmd/poller/poller.go
cmd/tools/doctor/restZapiDiff.go
cmd/tools/grafana/grafana.go
cmd/tools/rest/client.go
pkg/api/ontapi/zapi/client.go

- enable linters: bodyclose, nilerr
- disable linters: structcheck until it works with 1.18+
- fix all lint warnings

ci: bump golangci-lint

---

README.md
conf/README.md

With this change the only reference to Slack is the CHANGELOG.md
```bash
rg --files-with-matches --iglob !vendor -i slack
CHANGELOG.md
```

docs: change references from Slack to Discord

---

docs/architecture/rest-collector.md
docs/architecture/rest-strategy.md

docs: REST strategy doc

---

integration/test/alert/alert.go
integration/test/all_ems_test.go
integration/test/bookend_ems_test.go

Out of 14 bookend ems, 3 ems are node-scoped. So, when we do POST call of issuing ems and/or resolving ems we are not sure that given ems will be raised by ONTAP as due to node level.

fix: skipped bookend ems whose key is node-name

---

cmd/collectors/commonutils.go
cmd/collectors/commonutils_test.go
cmd/collectors/rest/plugins/snapmirror/snapmirror.go
cmd/collectors/rest/plugins/volume/volume.go
cmd/collectors/zapi/plugins/snapmirror/snapmirror_test.go
conf/rest/9.12.0/snapmirror.yaml
grafana/dashboards/cmode/harvest_dashboard_snapmirror.json

Changes covered in REST:
1. SVM peer call:
To handle special case where peer svm name can be any alias 
Here, `vs4` is exist in both the clusters, so while svm peer operation, destination cluster has renamed svm to other alias name to make unique identification, Which could cause issue while we do join snapmirrors and volumes in PromQL.
```
ocum-mobility-01-02::> vserver peer show -vserver vs_test
Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
vs_test     vs4.1       peered       AFFA200-206-76-78 snapmirror     vs4
```
2. To pass extra field `expand` to get child level snapmirros when svmdr has initiated.
``` …
```

fix: snapmirror relationships from source side 

---

cmd/collectors/zapiperf/zapiperf.go
cmd/exporters/prometheus/prometheus.go
pkg/matrix/metric.go

Fixes #1309
Converting ONTAP histograms to Prometheus histograms requires making sense of ONTAP's counter labels since those labels need to be normalized into a bucket interval for Prometheus. It is not always possible to generically convert ONTAP labels, since differnt counter subsystems use different free-form text. There is no standard or schema for these label names.
Harvest currently handles histograms that use this form of labels:
- `<20us   6`
- `<6ms    1`
- `<10s    0`
- `>=120s  4`
In this example, if these metrics are from the `svm` object and the `cifs_latency_hist` counter they will be exported as shown below. Since microseconds are the smallest unit, all latencies will be normalized to microseconds.
```
svm_cifs_cifs_latency_hist_bucket{cluster="cluster1",datacenter="dc",svm= …
```

feat: export ONTAP histograms as Prometheus histograms

---

cmd/collectors/ems/README.md
cmd/collectors/ems/ems.go
cmd/collectors/rest/plugins/certificate/certificate.go
cmd/collectors/rest/plugins/svm/svm.go
cmd/collectors/rest/plugins/volume/volume.go
cmd/collectors/rest/rest.go
cmd/collectors/rest/templating.go
cmd/collectors/restperf/restperf.go
cmd/collectors/zapi/collector/zapi.go
cmd/collectors/zapiperf/zapiperf.go
cmd/exporters/prometheus/httpd.go
cmd/poller/collector/collector.go
grafana/dashboards/cmode/harvest_dashboard_metadata.json
pkg/errs/ontap.go

fix: ems collector failed to send autosupport
docs: fix spelling in ems docs

feat: collectors should log PollData, plugin times, and metadata

---

grafana/dashboards/cmode/cluster.json

Thanks to @faguayot and jf38800 for reporting

fix: Top Latency units should be microseconds not milliseconds

---

cmd/collectors/restperf/restperf.go

Fixes: #1375
The sensor and shelf plugins need a separate fix.

fix: don't add units as metric labels since it breaks InfluxDB exporter

---

conf/zapiperf/cdot/9.8.0/disk.yaml
grafana/dashboards/cmode/aggregate.json
grafana/dashboards/cmode/disk.json

Reverted the disk.yaml recent changes and handled in aggregate and disk dashboards accordingly.

fix: handle raidgroup/plex alongwith other changes

---

grafana/dashboards/cmode/cluster.json

With this changes,
- based on the clusters selected, `Nodes & Sybsystems` rows will be added for each cluster. all details inside the row are cluster scoped.
If all clusters:
If one cluster:
complete view:

fix: cluster dashboard panel changes

---

cmd/collectors/zapiperf/zapiperf.go
cmd/exporters/prometheus/prometheus.go

Fixes #1309
Before this change a template with a display name would fail to export.
After this change a template like this:
```yaml
name:                     CIFSvserver
query:                    cifs:vserver
object:                   svm_cifs
counters:
- cifs_ops                => ops     # type=array
- cifs_latency_hist       => foople  # type=histogram
```
will export like so
```
svm_cifs_foople_bucket{cluster="umeng-aff300-05-06",datacenter="dc-1",svm="vs_test4",le="6000"} 10
svm_cifs_op_count{cluster="umeng-aff300-05-06",datacenter="dc-1",svm="vs_test4",metric="GetAttr"} 0
```

fix: Harvest should use template display name when exporting histograms

---

grafana/dashboards/cmode/snapmirror.json

fix: snapmirror dashboard changes

---

cmd/collectors/zapi/plugins/snapmirror/snapmirror.go

Zapi With `expand=false`
Zapi With `expand=true` --> got added 16 constituent's relationships here
Rest with `expand=false`
Rest with `expand=true`

fix: dont export constituents relationships in SM

---

cmd/collectors/rest/plugins/snapmirror/snapmirror.go
cmd/collectors/rest/rest.go
cmd/collectors/restperf/restperf.go
conf/rest/9.12.0/snapmirror.yaml
conf/zapi/cdot/9.8.0/snapmirror.yaml
grafana/dashboards/cmode/snapmirror.json

LS(load sharing) relationships don't have `relationship_id` field in ZAPI/REST response, due to this, we either skip them or wrongly populate in Harvest.
Changes made:
- added instancekey as `relationship_id`+`destination_path`
- make sure ZAPI and REST collector would parse as expected
- make sure no impact in dashboard due to this
With this, We can now monitor LS relationships as well and can show in dashboard if required.

fix: handle LS relationships + handle dashboard

---

cmd/collectors/rest/plugins/shelf/shelf.go

In my system, datacenter `DC-01` is zapi collector and `DC` is rest collector.

fix: shelf child obj - status ok to normal

---

docs/install/containers.md

Pulled latest nightly and tried to see if commands in doc is working. Reference https://stackoverflow.com/a/56687449
Restart is not upgrading containers to latest image
simply up does

docs: docker upgrade instructions

---

cmd/tools/grafana/dashboard_test.go
grafana/dashboards/cmode/cdot.json
grafana/dashboards/cmode/cluster.json
grafana/dashboards/cmode/lun.json
grafana/dashboards/cmode/node.json
grafana/dashboards/cmode/power.json
grafana/dashboards/cmode/qtree.json
grafana/dashboards/cmode/shelf.json
grafana/dashboards/cmode/snapmirror.json
grafana/dashboards/cmode/svm.json
grafana/dashboards/cmode/volume.json

This PR covers these:
- calcs: should be minimum of `{mean, lastNotNull, max}`, exception: when `sum` exist, other calculation may not be exist
- displayMode: should be `table`, exception: `hidden`
- placement: `bottom`
Case1 for calculation missing:
```
dashboard_test.go:704: dashboard=cmode/snapmirror.json, panel=Destination Relationships per Node, calculation section(s) mean not found
dashboard_test.go:704: dashboard=cmode/snapmirror.json, panel=Destination - Break Operations, calculation section(s) mean not found
dashboard_test.go:704: dashboard=cmode/snapmirror.json, panel=Destination - Resync Operations, calculation section(s) mean not found
dashboard_test.go:704: dashboard=cmode/snapmirror.json, panel=Destination - Update Operations, calculation section(s) mean not found …
```

feat: added dashboard tests for legends details

---

grafana/dashboards/cmode/svm.json

Panels Detail:
**NVMe/FC Drilldown** -> Changes in 2 panels
**Copy Offload Drilldown** -> No changes required
**QoS Policy Group Drilldown** -> Changes in 3 panels
**QoS Policy Group Latency from Resource Drilldown** -> Changes in 9 panels
**Volume Capacity Drilldown** -> Changes in 7 panels

feat: topk support in svm dashboard - 3

---

grafana/dashboards/cmode/headroom.json

None of the node cpu in openlab have confidence factor higher than 1.

fix: available ops in headroom dashboard should be displayed as per confidence factor

---

cmd/collectors/zapi/plugins/certificate/certificate.go
conf/rest/9.12.0/security_certificate.yaml
conf/zapi/cdot/9.8.0/security_certificate.yaml

Compared ZAPI and REST, 
Security_certificate would have 2 metrics, 
1. security_certitifcate_labels which contains all labels
2. security_certificate_expiry_time timestamp of expiry

fix: removing status metric in security_cert as nowhere used

---

cmd/collectors/zapiperf/plugins/volume/volume.go
grafana/dashboards/cmode/aggregate.json

UI panels:
This panel has 2 info to be shown, second info is from ontap.
new metric from zapiperf:
metric labels for flexgroup:

feat: support aggr filter for flexgroup volumes

---

cmd/collectors/restperf/plugins/volume/volume.go
cmd/collectors/zapiperf/plugins/volume/volume.go
grafana/dashboards/cmode/aggregate.json

New `volume_aggr_labels` metric,
for Flexgroup,
for Flexvol,
other existing metrics,
for Flexgroup,
for Flexvol,

feat: support aggr filter chnages in zapiperf

---

conf/restperf/9.12.0/volume.yaml
conf/zapiperf/cdot/9.8.0/volume.yaml
grafana/dashboards/cmode/cdot.json
grafana/dashboards/cmode/cluster.json
grafana/dashboards/cmode/node.json

Node aggregation for volume perf metrics are used in these panels:
1. Node dashbord: 
Backend Drilldown panels: -> Values are matching with 1.6
2. Cdot dashboard:
Used avg of node_volume_avg_latency.  
3. Cluster dashboard:
Highlight panels: --> values are matching with 1.6
Side changes:
- one query `WAFL Write Cleaning` was hidden in 2.0, whereas 1.6 showing the same.
- changed few units such that same metric would have same units for all dashboard.

feat: support node aggregation for flexgroup also

---

cmd/tools/grafana/dashboard_test.go
grafana/dashboards/cmode/fsa.json

fix: topk in table and info expanded as default in fsa dashboard

---

cmd/collectors/rest/plugins/qtree/qtree.go
conf/rest/9.12.0/qtree.yaml

Tested with REST collector, 
metrics behaviour in Harvest 22.05 
**qtree_labels:**
**qtree_disk_limit:**
**quota_disk_limit:**
metrics behaviour in latest Harvest
Case1: **Same behaviour as Harvest 22.05**
with hidden key-val pair
**qtree_labels:**
**qtree_disk_limit:**
**quota_disk_limit:**
Case2: **Current Harvest behaviour**
without hidden key-val pair:
**qtree_labels:**
**qtree_disk_limit:**
**quota_disk_limit:**

fix: backward compatibility for qtree metrics in rest

---

cmd/tools/grafana/units.yaml
grafana/dashboards/cmode/disk.json

Thanks to alessandro.nuzzo on [Discord](https://discord.com/channels/855068651522490400/1087393379203166258/1087393379203166258) for raising

fix: user read|write panels should use power of two bytes

---

cmd/collectors/rest/plugins/securityaccount/securityaccount.go

Issue:
we are creating new matrix from plugin(with more instances as part of array handling), So this new matrix can't be visible from template and any other plugin which would be used in template, which cause no effect of any `label_agent` or `metric_agent` plugin used in template.
Fix:
Instead of creating new matrix from plugin, we should create more instances in actual matrix(data) itself, so all the plugin s available in template can be applied on it and it would work as design.
zapi/rest metric count of labels:
activediruser:
certificateusers:
Same applies for all.

fix: fixing security account plugin generated metrics

---

.github/workflows/go.yml
.github/workflows/golangci-lint.yml
Makefile
cmd/poller/plugin/aggregator/aggregator_test.go
cmd/poller/plugin/labelagent/label_agent_test.go
cmd/poller/plugin/metricagent/metric_agent_test.go

fix: tests should pass regardless of execution order
ci: upgrade actions/setup-go to use cached installs

feat: go test should detect races and order dependent tests

---

grafana/dashboards/cmode/smb2.json
grafana/dashboards/cmode/svm.json

Light Theme Before:
Light Theme After:
Dark Theme Before:
Dark Theme After:

fix: change color scheme for heatmaps

---

.github/workflows/go.yml
.github/workflows/golangci-lint.yml
integration/Jenkinsfile
jenkins/artifacts/jenkinsfile

govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.
Using go1.20.1 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 2023-04-05 21:13:07 +0000 UTC).
Scanning your code and 195 packages across 30 dependent modules for known vulnerabilities...
Your code is affected by 3 vulnerabilities from the Go standard library.
Vulnerability #1: GO-2023-1705
Multipart form parsing can consume large amounts of CPU and
memory when processing form inputs containing very large numbers
of parts. This stems from several causes: 1.
mime/multipart.Reader.ReadForm limits the total memory a parsed
multipart form can consume. ReadForm can undercount the amount
of memory consumed, leading it to accept larger inputs than
intended. 2. …

chore: update golang to 1.20.3

---

cmd/poller/collector/helpers.go

Tested locally with `custom.yaml` file with this content
```
objects:
Status_7mode:    status_7_custom.yaml
```
```
./bin/poller -p sarzapi --promPort 13006 -o Status_7mode -c Zapi --config harvestopenlab.yml
2023-04-12T14:12:32+05:30 INF ./poller.go:205 > Init Poller=sarzapi configPath=harvestopenlab.yml logLevel=info version="harvest version 23.04.1214-v23.02.0 (commit d830c6c7) (build date 2023-04-12T14:12:12+0530) darwin/amd64\n"
2023-04-12T14:12:32+05:30 INF ./poller.go:242 > started in foreground Poller=sarzapi pid=88976
2023-04-12T14:12:33+05:30 INF ./poller.go:1215 > Use ZAPIs HARVEST_NO_COLLECTOR_UPGRADE= Poller=sarzapi collector=Zapi preferZAPI=true v=9.12.1
2023-04-12T14:12:34+05:30 WRN ./poller.go:331 > no collectors initialized, stopping Poller=sarzapi …
```

fix: handle custom file of status_7mode object

---

grafana/dashboards/storagegrid/overview.json

fix: StorageGRID overview panel is a missing query

---

container/prometheus/ems_alert_rules.yml

Instead of using static 'critical', use label 'severity' coming from EMS and maps to recommended prometheus scale of info/warning/critical: https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations
Known severity from ems: emergency, alert, error, informational, and notice
Severities suggested for use in alertmanager/prom: critical/warning/info.

feat: map ems severity to prom sev

---

integration/test/alert/alert.go

All mediator ems are having bookendkey as `ipaddress`.
Only `sm.mediator.misconfigured` ems has arg order change, rest all have first arg as ipaddress only same as resolving ems `sm.mediator.in.quorum`.

ci: mediator related ems changes in ci

---

cmd/collectors/zapi/plugins/qtree/qtree.go

fix: 7mode qtree key order in plugin

---

grafana/dashboards/7mode/disk7.json
grafana/dashboards/cmode/disk.json

fix: disk dashboard power on time should use `seconds` unit

---

cmd/collectors/collectorstest.go
cmd/collectors/rest/rest.go
cmd/collectors/rest/rest_test.go
cmd/collectors/restperf/restperf_test.go
cmd/poller/collector/collector.go

refactor: move unit testing json parser to common

---

cmd/collectors/restperf/restperf.go
conf/restperf/9.12.0/workload_detail.yaml
conf/restperf/9.12.0/workload_detail_volume.yaml
jenkins/artifacts/jenkinsfile

Although the value of `resource_name` should be `resource.name`, we are not currently utilizing it. Instead, we set the resource at the metric level, rather than at the instance level. The resource is retrieved from the instance key. It is worth noting that this warning in the log does not have any functional impact.
I have also changed this warning to error just like in Rest Collector.

fix: workload missing label value

---

cmd/poller/collector/asup.go

feat: Harvest should include numPollers and RSS in autosupport

---

cmd/collectors/zapi/plugins/qtree/qtree.go

Tested with customer's qtree-list response data.
Qtree instance keys are based on ONTAP response not the order in template:
Added logs in `SearchContent` function to validate it. Volume would always be first in key than tree.
```
-> current_path=[]      new_path=[qtree-info]
-> current_path=[qtree-info]    new_path=[qtree-info volume]
MATCH!
[qtree-info volume]
-> current_path=[qtree-info]    new_path=[qtree-info qtree]
MATCH!
[qtree-info qtree]
-> current_path=[qtree-info]    new_path=[qtree-info id]
-> current_path=[qtree-info]    new_path=[qtree-info oplocks]
-> current_path=[qtree-info]    new_path=[qtree-info security-style]
-> current_path=[qtree-info]    new_path=[qtree-info status]
```

fix: fix key for qtree 7mode

---

.github/workflows/go.yml
.github/workflows/golangci-lint.yml
integration/Jenkinsfile
jenkins/artifacts/jenkinsfile

updated due to govulcheck issue
Using go1.20.5
and govulncheck@v0.2.0 with vulnerability data from https://vuln.go.dev (last modified 2023-07-[11](https://github.com/NetApp/harvest/actions/runs/5529819307/jobs/10088396504?pr=2204#step:5:12) 19:19:08 +0000 UTC).
Scanning your code and 195 packages across 30 dependent modules for known vulnerabilities...
Vulnerability #1: GO-2023-1878
Insufficient sanitization of Host header in net/http
More info: https://pkg.go.dev/vuln/GO-2023-1878
Standard library
Found in: net/http@go1.20.5
Fixed in: net/http@go1.20.6
Example traces found:
Error:       #1: cmd/poller/poller.go:1064:31: poller.Poller.publishDetails calls http.Client.CloseIdleConnections
Error:       #2: cmd/exporters/influxdb/influxdb.go:2[13](https://github.com/NetApp/harvest/actions/run …

chore: bump go

---

cmd/collectors/storagegrid/rest/client.go
cmd/tools/rest/client.go
pkg/api/ontapi/zapi/client.go
pkg/auth/auth.go
pkg/auth/auth_test.go
pkg/auth/testdata/get_pass2

feat: when using a credential script, re-auth on 401s

---

cmd/collectors/storagegrid/rest/client.go
cmd/exporters/influxdb/influxdb.go
cmd/poller/poller.go
cmd/tools/grafana/grafana.go
cmd/tools/rest/client.go
integration/test/utils/http_utils.go
pkg/api/ontapi/zapi/client.go
pkg/requests/requests.go

Examples:
- `Harvest/23.07.2012` (date +%Y.%m.%d%H)
- `Harvest/2.0.2`

feat: Harvest should include a user agent

---

cmd/collectors/rest/plugins/disk/disk.go
cmd/collectors/rest/plugins/qtree/qtree.go
cmd/collectors/restperf/plugins/disk/disk.go
cmd/collectors/restperf/plugins/headroom/headroom.go
cmd/collectors/restperf/plugins/nic/nic.go
cmd/collectors/zapi/plugins/qtree/qtree.go
cmd/collectors/zapiperf/plugins/disk/disk.go
cmd/collectors/zapiperf/plugins/fcvi/fcvi.go
cmd/collectors/zapiperf/plugins/headroom/headroom.go
cmd/collectors/zapiperf/plugins/nic/nic.go
cmd/poller/exporter/exporter.go
cmd/poller/poller.go
go.mod
go.sum
pkg/matrix/errors.go
pkg/matrix/matrix.go
pkg/tree/xml/xml.go
vendor/github.com/go-openapi/jsonpointer/pointer.go
vendor/modules.txt

refactor: fix receive has generic name
refactor: Unquoted port mapping not recommended
refactor: delete redundant size hint
refactor: don't alias imported package name
refactor: Type assertion on errors fail on wrapped errors

refactor: fix inconsistent pointer receivers

---

cmd/tools/grafana/dashboard_test.go

Before
dashboard_test.go:1185: dashboard=cmode/node.json should have sorted keys but does not.Sorted version created at path=/tmp/cmode/node.json. Run cp /tmp/cmode/node.json cmode/node.json
After
dashboard_test.go:1186: dashboard=grafana/dashboards/cmode/node.json should have sorted keys but does not.Sorted version created at path=/tmp/cmode/node.json. Run **cp /tmp/cmode/node.json grafana/dashboards/cmode/node.json**

refactor: add cp command in dashboard sort test

---

Makefile

suppresses below
`ls: ./bin/*: No such file or directory`

fix: add bin dir check before removing files

---

conf/rest/9.10.0/volume.yaml
conf/zapi/cdot/9.8.0/volume.yaml
grafana/dashboards/cmode/volume.json

We can target this for 23.08. Looks low risk.
added in 9.6 for Rest Collector

feat: add junction paths in Volumes Dashboard

---

Makefile

#2289 didn't fix the issue. If bin dir is empty then , We still get below printed. Changing to `find`
`ls: ./bin/*: No such file or directory`

fix: bin dir prints error when there are no files in it

---

cmd/collectors/collectorstest.go
cmd/collectors/restperf/restperf.go
cmd/collectors/storagegrid/plugins/joinrest/joinrest.go
cmd/collectors/storagegrid/rest/client.go
cmd/tools/rest/client.go
cmd/tools/rest/rest.go

**BenchStat**
```
benchstat old.txt new.txt                                                                                              
goos: darwin
goarch: amd64
pkg: github.com/netapp/harvest/v2/cmd/tools/rest
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Run-8   175.5m ± 3%   167.8m ± 1%  -4.39% (p=0.000 n=20)
│    old.txt    │               new.txt                │
│     B/op      │     B/op      vs base                │
Run-8   29.432Mi ± 0%   4.494Mi ± 0%  -84.73% (p=0.000 n=20)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
Run-8   23.00 ± 0%   20.00 ± 0%  -13.04% (p=0.000 n=20)
```
**GetManyBytes**
```
goos: darwin …
```

perf: use parse instead of getMany for gjson

---

cmd/collectors/sensor_test.go
pkg/api/ontapi/zapi/client.go
pkg/tree/tree.go
pkg/tree/xml/xml.go

This reverts commit 1489cfc7da74dafd23c36030afce2846e7fa2e60.
Change done in #2380, reduces allocs but also increases parse time for xml payload due to streaming. Reverting the changes.
```
2023-09-29T01:59:40+05:30 INF collector/collector.go:485 > Collected Poller=dc-1 apiMs=15772 calcMs=0 collector=ZapiPerf:WorkloadDetailVolume instances=3360 metrics=20160 parseMs=37599 pluginMs=0 skips=0
```

revert: "perf: Zapi allocs improvements (#2380)"

---

conf/rest/9.6.0/cifs_share.yaml
conf/rest/default.yaml
conf/zapi/cdot/9.8.0/cifs_share.yaml
conf/zapi/default.yaml

Public API [/protocols/cifs/shares](https://library.netapp.com/ecmdocs/ECMLP2885799/html/#docs-NAS-protocols_cifs_shares) does not have the property named `properties`. The private CLI does so we'll use it.

feat: cifs share templates

---

cmd/collectors/fabricpool.go
grafana/dashboards/cmode/volume.json

Earlier behaviour:
`cloud_target` label can be non-deterministic as it depends on first constituent.
Current behaviour:
Now, we are handling fg instance based on the `cloud_target` label.
This is same behaviour for flexvols. All flexvols are also showing 2 records, 1 with cloud_target and other without cloud_target. 
Grafana UI panels:

fix: handled cloud_target for fabricpool

---

conf/zapiperf/cdot/9.8.0/rwctx.yaml
conf/zapiperf/default.yaml
grafana/dashboards/cmode/node.json

Tasks required for this feature.

feat: adding rw_ctx zapiperf object template

---

jenkins/artifacts/jenkinsfile

Updated to the versions used by build servers

ci: keep mkdocs version fixed for build servers

---

grafana/dashboards/cmode/workload.json

Comibination of `datacenter,cluster,policy_group` should still be unique as duplicate policy_group names are not allowed in cluster.

fix: QOS fixed% should include admin svm qos policy

---

pkg/matrix/matrix.go
pkg/matrix/metric_test.go

Because of this issue, harvest latency metrics may intermittently have spikes. These spikes are delta values, not average values.

fix: intermittent latency spike

---

docs/configure-ems.md

Added [discord](https://discord.com/channels/855068651522490400/1186441557239402496) question answer. There is a default `look back` time of 3 minutes for EMS collector for startup. I am not sure if highlighting this default startup behaviour is necessary.

doc: ems doc update

---

cmd/collectors/restperf/plugins/disk/disk.go
conf/restperf/9.12.0/disk.yaml

RestPerf Disk Plugin now supports Metric Customization via template changes.
This will support multi instance key as well
```
- paths => multipath:
storage-shelf-path-info:
- ^^controller => node
- ^^initiator-wwpn => wwpn
```

feat: RestPerf Disk Plugin should Support Metric Customization

---

conf/restperf/default.yaml
conf/zapiperf/default.yaml

Disable **4** templates from ZapiPerf and **3** templates from RestPerf.
As discussed, we will disable the few templates where no counters are used in any dashboards and leave remaining template as-is. So, closing this PR https://github.com/NetApp/harvest/pull/2507.

feat: disabled the templates whose all metrics are not consumed in dashboards

---

docs/prepare-cdot-clusters.md
integration/test/copy_logs_test.go

doc: add RBAC for `/support/autosupport`

ci: detect poller logs errors

---

cmd/tools/grafana/grafana.go

feat: add grafana customize command

---

conf/rest/9.7.0/ndmp_sessions.yaml
conf/rest/default.yaml
integration/test/dashboard_json_test.go

feat: adding ndmp session rest template

---

grafana/dashboards/cmode/node.json

feat: Change stat panel for uptime,power status,fan status to table in node dashboard

---

cmd/collectors/rest/rest.go
cmd/collectors/rest/rest_test.go

The rest collector's `api_time` only records how long it took for the first query in the rest template to execute, ignoring any endpoint times. Templates with multiple endpoints undercount the `api_time`. This pull request fixes the bug by including all endpoints `api_time`s in the reported `api_time`.

fix: rest collector should include endpoint `api_time`s

---

cmd/tools/grafana/grafana.go
cmd/tools/grafana/grafana_test.go
docs/dashboards.md
grafana/datasources/datasource.yml
integration/test/utils/utils.go

Task to be completed with this PR
--------------------------------------
**Grafana test cases covered.**
**1. No datasource in grafana**
**a. normal cli -> fail**
```
harvest % ./bin/harvest grafana import
using API token from config
A Prometheus-typed datasource named "prometheus" does not exist in Grafana.                                                                        
```
**b. normal cli with force -> pass dashboards empty and not populating data as absense of datasource**
```
harvest % ./bin/harvest grafana import --force
using API token from config
connected to Grafana server (version: 10.3.1)
created Grafana folder [Harvest-24.02.2615-cDOT] - OK
created Grafana folder [Harvest-24.02.2615-7mode] - OK
created Grafana folder [Harvest-24.02.2615-StorageGrid] - OK
preparing to …
```

feat: dashboards would work with grafana 10.x.x

---

cmd/tools/doctor/doctor.go
docs/configure-harvest-advanced.md
pkg/conf/conf.go
pkg/conf/expanders.go
pkg/conf/expanders_test.go

feat: add harvest.yml environment variable expansion

---

cmd/collectors/zapi/plugins/qospolicyfixed/qospolicyfixed.go
cmd/collectors/zapi/plugins/qospolicyfixed/qospolicyfixed_test.go

ONTAP CLI:
**Before**: qos_policy_adaptive_labels
**After:** qos_policy_adaptive_labels
**Before**: qos_policy_adaptive_peak_iops
**After:** qos_policy_adaptive_peak_iops
**Before**: qos_policy_adaptive_expected_iops
**After:** qos_policy_adaptive_expected_iops

fix: convert QOS Adaptive Policy Configuration ops to TB

---

conf/rest/9.10.0/lock.yaml
conf/rest/default.yaml
conf/zapi/cdot/9.8.0/lock.yaml
conf/zapi/default.yaml

Adding the zapi template for lock-get-iter.
With these below promQL queries, we can get lock count by volume, vserver, lif, node and cluster level and use them for alerting purpose.

feat: Adding zapi/rest templates for lock-get-iter & protocols/locks

---

conf/rest/9.10.0/lock.yaml
conf/zapi/cdot/9.8.0/lock.yaml

```
harvest % ./bin/poller -p sarzapi -o Lock --promPort 13001
2024-03-15T15:31:45+05:30 INF poller/poller.go:215 > Init Poller=sarzapi asup=false confPath=conf config=harvest.yml configPath=harvest.yml daemon=false debug=false homePath= hostname=hardikl-mac-0 logLevel=info logPath=/var/log/harvest/ profiling=0 promPort=13002 version="harvest version 24.03.15-1 (commit b3963467) (build date 2024-03-15T15:27:08+0530) darwin/amd64"
2024-03-15T15:31:45+05:30 INF poller/poller.go:239 > started in foreground Poller=sarzapi pid=7336
2024-03-15T15:31:48+05:30 INF collector/helpers.go:84 > best-fit template Poller=sarzapi collector=Zapi:Lock path=conf/zapi/cdot/9.8.0/lock.yaml v=9.13.1
2024-03-15T15:31:49+05:30 WRN poller/poller.go:687 > init collector-object error="no best-fit template for  on …
```

feat: changed plugin generated metric naming for lock object

---

cmd/collectors/restperf/restperf.go
cmd/poller/collector/collector.go
pkg/errs/ontap.go

The collector will retry after 30 to 60 seconds

feat: Harvest should handle ONTAP counter manager rejection errors

---

cmd/collectors/zapi/plugins/qospolicyfixed/qospolicyfixed.go
cmd/collectors/zapi/plugins/qospolicyfixed/qospolicyfixed_test.go

This happens on ONTAP 9.1.X
```
qos policy-group show -fields ?
policy-group                Policy Group Name
vserver                     Vserver
uuid                        Uuid
class                       Policy Group Class
pgid                        Policy Group ID
max-throughput              Maximum Throughput
num-workloads               Number of Workloads
throughput-policy           Throughput Policy
```

fix: QosPolicyFixed should ignore missing min-throughput

---

cmd/tools/grafana/dashboard_test.go
grafana/dashboards/cmode/volume.json

Panels are available in `Volume Growth rate` dashboard for review in .127 system.

feat: Adding volume growth rate panels in volume dashboard

---

cmd/collectors/commonutils.go
cmd/collectors/ems/ems.go
cmd/collectors/storagegrid/storagegrid.go
cmd/collectors/zapi/plugins/aggregate/aggregate.go
cmd/collectors/zapi/plugins/svm/svm.go
cmd/collectors/zapiperf/plugins/disk/disk.go
cmd/collectors/zapiperf/zapiperf.go
cmd/poller/collector/collector.go

Based on the logs shared by Tony earlier, found that the following logs are being generated frequently and do not seem useful at the debug level.
2516825 nabox-harvest2 | 2024-03-12T08:17:11Z DBG disk/disk.go:901 > failed to parse value error="strconv.ParseFloat: parsing \"-\": invalid syntax" Poller=metricKey=fan-rpm object=Disk plugin=ZapiPerf:Disk value=-
569724 nabox-harvest2 | --- DBG --- > --- --- data --- --- --- --- ---
417831 nabox-harvest2 | 2024-03-12T08:15:57Z DBG zapiperf/zapiperf.go:1669 > instances Poller=collector=ZapiPerf:FCVI new=0 removed=0 total=0
261276 nabox-harvest2 | --- DBG --- > --- --- --- --- --- ---
131129 nabox-harvest2 | 2024-03-12T08:15:59Z DBG collector/collector.go:509 > skipped non-exportable data Poller=UUID=Rest collector=Rest:Health object=health …

style: improving Debug Log Clarity and Reducing Noise

---

conf/restperf/9.12.0/disk.yaml

job v3 are restperf records and job v4 are zapiperf records.
**Prior:**
**With fix:**

fix: parity of id value in disk restperf and zapiperf

---

cmd/collectors/rest/plugins/volume/volume.go

**Prior the changes:**
```
harvest % ./bin/poller -p sar --promPort 18002  -o Volume -c Rest
2024-04-16T17:37:02+05:30 INF poller/poller.go:221 > Init Poller=sar asup=false confPath=conf config=harvest.yml configPath=harvest.yml cwd=/Users/hardikl/Documents/Harvest/harvest daemon=false debug=false homePath= hostname=hardikl-mac-0 logLevel=info logPath=/var/log/harvest/ profiling=0 promPort=18002 version="harvest version 24.04.16-1 (commit 88070726) (build date 2024-04-16T17:36:37+0530) darwin/amd64"
2024-04-16T17:37:02+05:30 INF poller/poller.go:245 > started in foreground Poller=sar pid=39528
2024-04-16T17:37:03+05:30 INF collector/helpers.go:88 > best-fit template Poller=sar collector=Rest:Volume path=conf/rest/9.12.0/volume.yaml v=9.13.1
2024-04-16T17:37:04+05:30 INF …
```

refactor: fetch constituents when asked from template

---

cmd/tools/grafana/dashboard_test.go

before the fix:
After the fix, it was working as expoected.

fix: fix dashboard sort test

---

cmd/collectors/rest/plugins/qtree/qtree.go
cmd/collectors/zapi/plugins/qtree/qtree.go

```yaml
plugins:
- LabelAgent:
exclude_equals:
- qtree ``
- Qtree:
qtreeMetrics: true                            # <== Add this for backward compatibility
objects:
- disk-limit
- disk-used
- disk-used-pct-disk-limit
- disk-used-pct-soft-disk-limit
- disk-used-pct-threshold
- file-limit
- files-used
- files-used-pct-file-limit
- files-used-pct-soft-file-limit
- soft-disk-limit
- soft-file-limit
- threshold
quotaType:
- tree
```

feat: remove duplicate quota metrics

---

cmd/tools/grafana/dashboard_test.go
grafana/dashboards/cmode/aggregate.json
grafana/dashboards/cmode/data_protection_snapshot.json
grafana/dashboards/cmode/datacenter.json
grafana/dashboards/cmode/details/volumeBySVM.json
grafana/dashboards/cmode/details/volumeDeepDive.json
grafana/dashboards/cmode/disk.json
grafana/dashboards/cmode/external_service_op.json
grafana/dashboards/cmode/lun.json
grafana/dashboards/cmode/mcc_cluster.json
grafana/dashboards/cmode/network.json
grafana/dashboards/cmode/nfsTroubleshooting.json
grafana/dashboards/cmode/node.json
grafana/dashboards/cmode/power.json
grafana/dashboards/cmode/security.json
grafana/dashboards/cmode/snapmirror.json

With this PR change, Only these panels are pending and we can target them in next release
```
// we don't get description for below panels, we need to manually formed them as per our need.
ignoreList := []string{
// These are from fsa
"Volume Access ($Activity) History", "Volume Access ($Activity) History By Percent", "Volume Modify ($Activity) History", "Volume Modify ($Activity) History By Percent",
// This is from workload
"Top $TopResources Workloads by Service Time from sync_repl", "Top $TopResources Workloads by Service Time from flexcache_ral", "Top $TopResources Workloads by Service Time from flexcache_spinhi",
"Top $TopResources Workloads by Latency from sync_repl", "Top $TopResources Workloads by Latency from flexcache_ral", "Top $TopResources Workloads by Latency from …
```

feat: adding description to panels

---

cmd/collectors/rest/plugins/volume/volume.go

fix: handling missing protection_mode in disk rest call

---

cmd/tools/generate/counter.go
cmd/tools/generate/counter.yaml
docs/ontap-metrics.md

```
| Missing Mappings      |       Counter Name                                            |       APIs |
| Missing REST mapping  |       aggr_snapshot_inode_used_percent                        |       [API: ZAPI, Endpoint: aggr-get-iter, ONTAPCounter: aggr-attributes.aggr-snapshot-attributes.percent-inode-used-capacity, Template: conf/zapi/cdot/9.8.0/aggr.yaml] |
| Missing REST mapping  |       aggr_space_reserved                                     |       [API: ZAPI, Endpoint: aggr-get-iter, ONTAPCounter: aggr-attributes.aggr-space-attributes.total-reserved-space, Template: conf/zapi/cdot/9.8.0/aggr.yaml] |
| Missing REST mapping  |       flexcache_blocks_requested_from_client                  |       [API: ZAPI, Endpoint: perf-object-get-instances flexcache_per_volume, ONTAPCounter: …
```

doc: 24.05 ontap metric docs

---

cmd/collectors/zapi/plugins/qtree/qtree.go

2024-05-20T18:06:11+05:30 ERR collector/collector.go:453 > error="duplicate instance key => umeng-aff300-05-svm1.test1..root.file-limit" Poller=u2 collector=Zapi:Qtree plugin=Qtree

fix: duplicate instance key issue quota metrics

---

cmd/collectors/storagegrid/rest/client.go
third_party/go-version/LICENSE
third_party/go-version/README.md
third_party/go-version/constraint.go
third_party/go-version/version.go
third_party/go-version/version_collection.go

Bumps to https://github.com/hashicorp/go-version/releases/tag/v1.7.0

chore: bump hashicorp go-version

---

cmd/poller/poller.go
grafana/dashboards/cmode/metadata.json

fix: include pid in `poller_status`
fix: poller_memory should export metrics with KB units
fix: add variables to all Metadata dashboard panels queries

feat: include RSS in Poller table of Metadata dashboard

---

cmd/tools/grafana/grafana.go
integration/test/dashboard_test.go
integration/test/grafana/grafana_mgr.go

Thanks to Chris Gautcher (@gautcher) for raising.

fix: Harvest should log errors when grafana import fails

---

cmd/poller/collector/asup.go
cmd/poller/poller.go

MaxRss (in bytes) is updated once a minute
Example auto-support JSON
```json
"Harvest": {
"HostHash": "df62c133cbd0fef8ccda100e3c04c33eb3b2d911",
"UUID": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
"Version": "2.0.2",
"Release": "rc2",
"Commit": "HEAD",
"BuildDate": "undefined",
"NumClusters": 1,
"NumPollers": 27,
"NumExporters": 5,
"NumPortRange": 1,
"Pid": 48223,
"RssBytes": 17473536,
"MaxRssBytes": 17473536,
"EpochMilli": 1718201199682
}
```

feat: Harvest should track poller maxRSS in auto-support

---

cmd/collectors/power.go
cmd/collectors/sensor_test.go
cmd/collectors/testdata/rest-sensors-a1000.json
cmd/collectors/testdata/rest-sensors-a900.json

Those platforms have sensors with slightly different names that Harvest needs to accommodate.
Fixes: #3062

fix: Harvest should collect power metrics from a1000 and a900 clusters

---

cmd/collectors/rest/plugins/health/health.go

```
harvest % ./bin/poller -p sarzapi -o Health --promPort 13001
2024-07-30T15:19:53+05:30 INF poller/poller.go:227 > Init Poller=sarzapi asup=false confPath=conf config=harvest.yml configPath=harvest.yml cwd=/Users/hardikl/Documents/Harvest/harvest daemon=false homePath= hostname=hardikl-mac-0 logLevel=info logPath=/var/log/harvest/ profiling=0 promPort=13001 version="harvest version 24.07.30-1 (commit 9897862e) (build date 2024-07-30T15:11:58+0530) darwin/amd64"
2024-07-30T15:19:53+05:30 INF poller/poller.go:251 > started in foreground Poller=sarzapi pid=13159
2024-07-30T15:19:54+05:30 INF collector/helpers.go:97 > best-fit template Poller=sarzapi collector=Rest:Health jitter=none path=conf/rest/9.6.0/health.yaml v=9.15.1
2024-07-30T15:19:56+05:30 WRN poller/poller.go:762 > init …
```

feat: adding generated instances/metrics count in Health plugin log

---

cmd/poller/options/options.go
pkg/conf/conf.go
pkg/logging/logger.go

refactor: remove cyclic dependency in logging

perf: reduce allocs when reading credential files

---

cmd/poller/collector/asup.go
cmd/poller/plugin/labelagent/parse_rules.go

cmd/poller/plugin/labelagent/parse_rules.go:534:26: G115: integer overflow conversion uint64 -> uint8 (gosec)
r.defaultValue = uint8(v)
^
cmd/poller/plugin/labelagent/parse_rules.go:580:26: G115: integer overflow conversion uint64 -> uint8 (gosec)
r.defaultValue = uint8(v)
^
cmd/poller/collector/asup.go:421:20: G115: integer overflow conversion int -> uint8 (gosec)
return arch, uint8(cpuCount)

build: fix lint issues

---

pkg/auth/auth.go

Thanks to MichaelKnapp for reporting

fix: do not log stdout when a credential script fails

---

grafana/dashboards/cmode/workload.json

The `WorkloadClass` dropdown affects the data displayed in the `Workload` dropdown, so using "All" as the default option is not correct.

fix: Remove '*' as 'All' option in workload dropdown on workload dashboard

---

cmd/exporters/prometheus/prometheus.go

Remove unnecessary `Sprintf` and `strings.Join`

perf: reduce allocs in prometheus render

---

pkg/auth/auth.go

If a customer's script cmdPath contains credentials, do not log the exec.LookPath error since the cmdPath credentials may be logged too

refactor: change auth credential script logging to debug

---

cmd/exporters/prometheus/httpd.go
cmd/exporters/prometheus/prometheus_test.go

This PR uses HTTP chunking to stream the metrics instead of joining all the metrics and writing that single blob.
- Poll sar with single Rest volume collector
- curl metrics endpoint 240 times
- take heap dump and report on `alloc_space` bytes for `Prometheus.ServeMetrics`
Before change:
457.75 MB is alloced from `ServeMetrics`
After change:
1 MB is alloced from `ServeMetrics`
Thanks to ChrisGautcher for reporting

perf: reduce allocs when serving metrics

---

cmd/exporters/prometheus/prometheus.go
pkg/matrix/metric.go

This PR reduces allocations by an order of magnitude through two optimizations:
1. Avoiding slice reallocations
2. Rendering metrics into a shared buffer
- Poll sar with single RestPerf volume collector
- Changed collector.go to export each matrix 240 times
- Take heap dump and report on `alloc_space` bytes for `Prometheus.render`
Before change:
1.41 GB is alloced from `render`
After change:
124.64 MB is alloced from `render`
Thanks to ChrisGautcher for reporting

perf: reduce allocs when rendering metrics

---

cmd/tools/generate/counter.go
integration/test/dashboard_json_test.go

ci: integration tests should read KeyPerf definitions from the correct directory

ci: ignore volume_top_files_ counters

---

conf/ems/9.6.0/ems.yaml
container/prometheus/ems_alert_rules.yml
docs/resources/ems-alert-runbook.md
integration/test/alert_rule_test.go

feat: Harvest should monitor `wafl.dir.size.warning`

---

cmd/collectors/rest/rest.go
cmd/poller/collector/collector.go

when Metrocluster is not configured
Thanks to Francisca for raising.

fix: MetroclusterCheck collector should report "no instances"

---

cmd/collectors/restperf/plugins/volumetopmetrics/volumetopmetrics.go

time=2024-11-25T16:21:54.877+05:30 level=ERROR source=collector.go:305 msg="Collector panicked" Poller=fsx collector=RestPerf:Volume err="runtime error: invalid memory address or nil pointer dereference\n" stack="goroutine 126 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/opt/go/libexec/src/runtime/debug/stack.go:26 +0x64\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start.func1()\n\t/Users//GolandProjects/harvest/cmd/poller/collector/collector.go:308 +0x108\npanic({0x1031b1500?, 0x10366af40?})\n\t/opt/homebrew/opt/go/libexec/src/runtime/panic.go:785 +0xf0\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf/plugins/volumetopmetrics.(*TopMetrics).processTopClients(0x140001739a0, 0x0)\n\t/Users//GolandProjects/harvest/cmd/collectors/restperf/plugins/volumetop …

fix: panic if no volumes have analytics enabled

---

third_party/go-version/version.go
third_party/olekukonko/tablewriter/table.go

```
gotip vet ./...
third_party/go-version/version.go:402:20: non-constant format string in call to fmt.Fprintf
third_party/olekukonko/tablewriter/table.go:769:24: non-constant format string in call to fmt.Fprintf
```

ci: fix go vet errors

---

conf/rest/9.12.0/security_audit_dest.yaml

Tried with these records, 
```
{
"records": [
{
"address": "x.x.x.x",
"port": 6414,
"ipspace": {
"name": "Default",
"uuid": "d192470e-0580-11e8-bd9d-00a098d39e12"
},
"protocol": "tcp_encrypted",
"facility": "user",
"verify_server": true,
"message_format": "legacy_netapp",
"timestamp_format_override": "no_override",
"hostname_format_override": "no_override",
"_links": {
"self": {
"href": "/api/security/audit/destinations/x.x.x.x/6414"
}
}
},
{
"address": "x.x.x.x",
"port": 6514,
"ipspace": {
"name": "Default",
"uuid": "d192470e-0580-11e8-bd9d-00a098d39e12"
},
"protocol": "tcp_encrypted",
"facility": "user",
"verify_server": true,
"message_format": "legacy_netapp",
"timestamp_format_override": "no_override",
"hostname_format_override": "no_override",
"_links": {
"self": {
"href": …
```

fix: handled duplicate key in SecurityAuditDestination

---

CHANGELOG.md
autosupport/README.md
conf/rest/9.11.0/cloud_target.yaml
conf/rest/9.12.0/cloud_target.yaml
conf/zapi/cdot/9.10.0/aggr_object_store_config.yaml

access_key is considered personally identifiable information
Thanks to Piyush Gaur for reporting.
Fixes: #3469

fix: cloud target template should not export access_key

---

cmd/collectors/rest/plugins/clustersoftware/clustersoftware.go
grafana/dashboards/cmode/cluster.json

In case of this type of update_detail response, It's already discarding them with non-empty node name check at line 156.
```
"update_details": [
{
"phase": "ONTAP updates"
},
{
"phase": "ONTAP updates"
}
],
```
In case of this type of status_details, All the fields are same but start_time, so using it to differentiate them. 
```
{
"node": {
"name": "cl-01"
},
"name": "do-download-job",
"state": "failed",
"issue": {
"message": "Image update failed to start. Reason: Software update/install already in progress",
"code": 10551404
},
"action": {
"message": "Use the \"cluster show\" command to verify that all nodes in the cluster are healthy. Use the \"cluster image package show-repository\" command to verify that the downloaded image has the correct version. If all nodes are healthy and the …
```

feat: handled duplicate instance issue in clustersoftware plugin

---

cmd/collectors/commonutils.go
cmd/collectors/restperf/plugins/vscan/test_nonvalid_vscan.json
cmd/collectors/restperf/plugins/vscan/test_valid_vscan.json
cmd/collectors/restperf/plugins/vscan/vscan_test.go

This change would be handling 2 cases,
1. When aggregation is enabled(which is default), Making each instance to false in 2nd loop instead of 1st loop.
2. When scanner value is empty, don't proceed and jump to next iteration for both the loops. -> Earlier no instances were created for this kind of bad data in 1st loop and 2nd loop would fail when no instance has been found.

fix: handled empty scanner and export false case for vscan

---

conf/rest/9.12.0/ems_destination.yaml

time=2025-05-05T13:03:49.844+05:30 level=ERROR source=collector.go:436 msg="" Poller=vsim collector=Rest:EmsDestination error="failed to fetch data: error making request StatusCode: 400, Message: The value \"filter\" is invalid for field \"fields\" (<field,...>), Code: 262197, Target: fields, API: /api/support/ems/destinations?fields=certificate.ca%2Cdestination%2Cfilter%2Cname%2Csyslog%2Csystem_defined%2Ctype&max_records=500&return_records=true&system_defined=false" task=data

fix: filter label for ems destination is missing

---

cmd/collectors/rest/plugins/vscanpool/vscanpool.go

Noticed on `.74`
This is happening because the plugin is asking for a field that does not exist on ONTAP version 9.9.1.
time=2025-05-16T11:34:13.431-04:00 level=ERROR source=vscanpool.go:91 msg="Failed to collect vscan server info data" Poller=umeng_aff300 plugin=Rest:VscanPool object=Vscan error="failed to fetchAll href=api/protocols/vscan/server-status..., hrefLength=131 err=error making request StatusCode: 400, Message: The value \"interface.name\" is invalid for field \"fields\" (<field,...>), Code: 262197, Target: fields, API: /api/protocols/vscan/server-status?fields=interface.name%2Cip%2Cnode.name%2Cstate%2Csvm.name%2Cupdate_time&max_records=500&return_records=true"

fix: Vscanpool plugin should only ask for fields it uses

---

cmd/collectors/rest/rest.go
cmd/collectors/zapi/collector/zapi.go
cmd/collectors/zapi/plugins/volume/volume.go

No changes are needed for the Perf collectors, as they reset the exportable while handling partial aggregation.

feat: instance exportable handling for Rest/Zapi collector

---

grafana/dashboards/storagegrid/overview.json

Performance > "Average request duration (non-error)" panel should include units.
feat: Include HEAD and POST requests in the panel
Thanks @mamoep for raising.
Fixes: #3736

fix: StorageGRID panel should include units

---

.golangci.yml

See https://github.com/golangci/golangci-lint/issues/3228

ci: disable nolintlint due to false positives
